import { createContext, useContext, useState, useEffect, useMemo, useCallback } from 'react'

const LanguageContext = createContext(null)

export const LANG_NAMES = {
  en: 'English',
  hi: 'हिन्दी (Hindi)',
  te: 'తెలుగు (Telugu)',
  es: 'Español (Spanish)',
}

const TRANSLATIONS = {
  en: {
    home: 'Home',
    searchMedicines: 'Search Medicines',
    howAvailabilityWorks: 'How Availability Works',
    savedMedicines: 'Saved Medicines',
    zoikoSignal: 'ZoikoSignal™',
    notifications: 'Notifications',
    myProfile: 'My Profile',
    settings: 'Settings',
    helpSupport: 'Help & Support',
    signOut: 'Sign Out',
    myMedicines: 'My Medicines',
    account: 'Account',
    support: 'Support',
    findAvailability: 'Find medicine availability near you',
    heroSubtitle: 'Search a medicine to see real-time availability confidence from verified pharmacies — powered by MediBase™ and governed data.',
    searchPlaceholder: 'Search by medicine, brand name, active ingredient, or generic...',
    scanPrescription: 'Scan a prescription',
    scanDesc: 'Snap or upload it — we extract the medicines for you.',
    popularSearches: 'POPULAR:',
    apply: 'Apply',
    languageUpdated: 'Language preference updated',
    settingsSubtitle: 'Language, accessibility, and location preferences.',
    languageAndRegion: 'Language & region',
    chooseLanguage: 'Choose your preferred interface language.',
    accessibility: 'Accessibility (WCAG 2.2 AA)',
    accessibilityDesc: 'Make the interface easier to read and use.',
    largerText: 'Larger text',
    largerTextDesc: 'Increase label and body text size.',
    reduceMotion: 'Reduce motion',
    reduceMotionDesc: 'Minimize animations and transitions.',
    locationAndData: 'Location & data',
    clearLocationDesc: 'Clear the location saved on this device.',
    clearLocationBtn: 'Clear saved location',
    contactDetails: 'Contact details',
    updateContactDesc: 'Update how verified pharmacies and ZoikoMeds can reach you.',
    fullName: 'Full name',
    emailAddress: 'Email address',
    phone: 'Phone',
    saveChanges: 'Save changes',
    password: 'Password',
    updatePasswordDesc: 'Update your account password.',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmNewPassword: 'Confirm new password',
    updatePasswordBtn: 'Update password',
    searchByName: 'Search by name',
    medicineName: 'MEDICINE NAME',
    searchArea: 'SEARCH AREA',
    useMyLocation: 'Use my location',
    usingCurrentLocation: 'Using your current location',
    locationSet: 'Location set',
    undo: 'Undo',
    searchAvailability: 'Search Availability',
    distanceFromMe: 'Distance from me:',
    km: 'km',
    verifiedNetwork: 'Verified pharmacy network',
    privacySafe: 'Privacy-safe search',
    noExactQuantities: 'No exact stock quantities',
    availabilityNearYou: 'Availability near you',
    whatDoesConfidenceMean: 'What does confidence mean?',
    emptySearchPrompt: 'Enter a medicine and tap Search Availability to see which nearby pharmacies are likely to have it.',
    checkingAvailability: 'Checking availability at nearby pharmacies…',
    noPharmaciesFound: 'No pharmacies found within the selected radius. Try a different location or increase the distance.',
    directions: 'Directions',
    callPharmacy: 'Call pharmacy',
    save: 'Save',
    saved: 'Saved',
    medicineNameHelp: 'Enter a medicine name only. Do not enter symptoms, diagnoses, insurance details, or prescription images.',
    searchAreaPlaceholder: 'City, ZIP code, or postcode',
    addLocationHelp: 'Add a location to see nearby pharmacies.',
    understandingAvailability: 'Understanding availability confidence',
    availabilitySubtitle: 'How ZoikoMeds shows whether a medicine is likely available near you — as a governed confidence signal, never a stock guarantee.',
    whatIsZoikoAvail: 'What is ZoikoAvail™?',
    whatIsZoikoAvailDesc: 'ZoikoAvail™ is the availability confidence engine behind ZoikoMeds. It takes availability signals shared by verified pharmacies and turns them into a simple confidence band, so you can judge how likely a medicine is to be available before you travel. It never exposes exact stock counts, and it never lets you reserve or buy — it is intelligence only.',
    confidenceLevels: 'Confidence levels',
    whyAvailabilityChanges: 'Why medicine availability changes',
    howPharmaciesKeepCurrent: 'How verified pharmacies keep it current',
    verifiedPharmaciesOnly: 'Verified pharmacies only',
    verifiedPharmaciesOnlyDesc: 'Signals come from pharmacies whose licences have been verified and who opt in to participate.',
    signalsNotStock: 'Signals, not stock counts',
    signalsNotStockDesc: 'Pharmacies share availability signals — we never expose exact quantities on hand.',
    freshnessWeighted: 'Freshness-weighted',
    freshnessWeightedDesc: 'ZoikoAvail™ weights each signal by how recent it is and the pharmacy’s reliability, then derives a confidence band.',
    searchMedicineAvailability: 'Search medicine availability',
    likelyAvailableNow: 'Likely available now',
    likelyAvailableNowDesc: 'A verified pharmacy shared a recent signal indicating this medicine is likely available now.',
    mayBeLimited: 'May be limited — confirm first',
    mayBeLimitedDesc: 'Signals suggest it may be available but could be limited. Confirm with the pharmacy before travelling.',
    notRecentlyConfirmed: 'Not recently confirmed',
    notRecentlyConfirmedDesc: 'Availability has not been confirmed recently. Treat this as uncertain and call ahead.',
    noRecentSignal: 'No recent signal',
    noRecentSignalDesc: 'No recent signal from verified pharmacies nearby. We cannot indicate availability right now.',
    search: 'Search',
    availability: 'Availability',
    savedMedicinesSubtitle: 'Track availability confidence for the medicines you follow across verified pharmacies.',
    noSavedMedicinesYet: 'No saved medicines yet',
    noSavedMedicinesDesc: 'Save a medicine from search or details page to track its availability confidence here.',
    alertsEnabled: 'Alerts enabled',
    viewDetails: 'View details',
    recentSearches: 'Recent searches',
    verifiedPharmacies: 'Verified pharmacies',
    activeAlerts: 'Active alerts',
    yourZoikoSignal: 'Your ZoikoSignal™',
    zoikoSignalDesc: 'Get alerts when saved medicines run low or return.',
    savedMedicinesDesc: 'Track availability for the medicines you follow.',
    feverPain: 'Fever & Pain',
    coldCough: 'Cold & Cough',
    diabetes: 'Diabetes',
    heartBp: 'Heart & BP',
    antibiotics: 'Antibiotics',
    acidity: 'Acidity',
    allergy: 'Allergy',
    vitamins: 'Vitamins',
    homeDisclaimer: 'Availability is a governed confidence signal from verified pharmacies — not exact stock. Please confirm with the pharmacy before visiting.',
    browseByHealthNeed: 'BROWSE BY HEALTH NEED',
    zoikoSignalSubtitle: 'Personalized medicine availability notifications for your saved medicines.',
    liveMonitoring: 'Live monitoring',
    markAllRead: 'Mark all read',
    runningLow: 'Medicines Running Low',
    backInStockToday: 'Back in Stock Today',
    allCaughtUp: "You're all caught up",
    noUrgentAlerts: 'No urgent availability alerts for your saved medicines right now.',
    mySavedMedicines: 'MY SAVED MEDICINES',
    searchSavedPlaceholder: 'Search saved medicines...',
    smartNotifications: 'SMART NOTIFICATIONS',
    all: 'All',
    unread: 'Unread',
    safetyAlerts: 'Safety Alerts',
    viewPharmacies: 'View Pharmacies',
    markRead: 'Mark read',
    archive: 'Archive',
    readAdvisory: 'Read advisory',
    readAnnouncement: 'Read Announcement',
    notificationsSubtitle: 'Platform updates, medicine safety alerts, stock availability notifications, and system messages.',
    announcements: 'Announcements',
    stockAlerts: 'Stock Alerts',
    safetyRecalls: 'Safety & Recalls',
    system: 'System',
    noNotifications: 'No notifications',
    notificationSettings: 'Notification settings',
    notificationSettingsDesc: 'Choose what ZoikoSignal™ tells you about — alerts are based on availability confidence, never exact stock.',
    availabilityAlerts: 'Availability alerts',
    runningLowTitle: 'Running low',
    runningLowDesc: 'Notify me when a saved medicine is running low near me.',
    backInStockTitle: 'Back in stock',
    backInStockDesc: 'Notify me when a saved medicine is available again.',
    nearbyRestockTitle: 'Nearby restock',
    nearbyRestockDesc: 'Notify me when a nearby pharmacy receives new stock.',
    safetyHeading: 'Safety',
    medicineRecallTitle: 'Medicine recall alerts',
    medicineRecallDesc: 'Manufacturer or regulator recall notices for medicines you follow.',
    governmentSafetyTitle: 'Government safety alerts',
    governmentSafetyDesc: 'National health advisories for your saved medicine classes.',
    channelsHeading: 'Channels',
    pushNotificationsTitle: 'Push notifications',
    pushNotificationsDesc: 'Receive alerts on this device.',
    emailNotificationsTitle: 'Email notifications',
    emailNotificationsDesc: 'Receive a summary by email.',
    smsNotificationsTitle: 'SMS notifications',
    smsNotificationsDesc: 'Receive urgent alerts by text message.',
    whyChange1: 'Pharmacies dispense stock throughout the day, so what was available this morning may not be by evening.',
    whyChange2: 'New deliveries and restocks arrive on different schedules for each pharmacy.',
    whyChange3: 'Regional demand and supply pressure (e.g. seasonal illness) shifts availability quickly.',
    whyChange4: 'A signal ages: the longer since a pharmacy last confirmed, the lower our confidence.',
    confirmNote: 'Availability does not mean a medicine is reserved for you. Always call or visit the pharmacy to confirm before travelling.',
    scopeNote: 'Availability intelligence only — not stock count, stock reservation, or online sale.',
    verifiedAccount: 'Verified account',
    readOnly: 'READ-ONLY',
    emailReadOnlyNotice: 'Email is linked to your login account and cannot be changed.',
    profilePrivacyNotice: 'ZoikoMeds does not collect prescriptions or health records. We store only the contact details you provide to power your alerts.',
    profileUpdated: 'Profile updated',
    passwordUpdated: 'Password updated',
    enterPassword: 'Enter password',
    passwordMinLength: 'Password must be at least 8 characters long.',
    passwordsDoNotMatch: 'Passwords do not match.',
    dropPrescriptionHere: 'Drop your prescription here',
    extractMedicineDesc: "We'll extract the medicine names — you choose which ones to search. Your image is never stored or shared.",
    browseFile: 'Browse file',
    maxFileNotice: 'JPG, PNG, PDF, HEIC — max 10 MB',
    or: 'or',
    takePhoto: 'Take a photo',
    fromGallery: 'From gallery',
    privacyNoticeTitle: 'Privacy notice:',
    prescriptionPrivacyNotice: 'Your prescription image is used only to extract medicine names for this search. It is never stored, shared, or used to identify you. ZoikoMeds does not process, validate, or fulfil prescriptions. No medical advice is provided.',
    yourLocationForNearbySearch: 'Your location (for nearby search)',
    useMyCurrentLocation: 'Use my current location',
    medicinesFound: 'medicines found',
    scanAnother: 'Scan another',
    chooseMedicinesToSearch: 'Choose which medicines to search for availability near you.',
    extractedNamesNotice: 'Extracted names are read from your image only. Confirm the exact medicine and strength with your prescription — ZoikoMeds does not validate prescriptions.',
    readingPrescription: 'Reading your prescription…',
    extractingNamesFrom: 'Extracting medicine names from',
    deviceOnlyNotice: 'This happens on your device — the image is not uploaded.',
    prescription: 'Prescription',
    otc: 'OTC',
    governedIdentityNotice: 'Governed medicine identity — MediBase™. Availability below is a confidence signal, not exact stock.',
    requiresConfirmation: 'Requires confirmation — call before visiting.',
    distance: 'Distance',
    signalUpdated: 'Signal updated',
    call: 'Call',
    morePharmaciesWeb: 'More pharmacies near you (from the web)',
    openNow: 'Open now',
    closed: 'Closed',
    rating: 'Rating',
    webPharmaciesDisclaimer: "Found on the web by location and outside the ZoikoMeds verified network. Stock isn't confirmed — please call ahead.",
    howAvailabilityWorksCaps: 'HOW AVAILABILITY WORKS',
    medibaseIdentifies: 'MediBase™ identifies the medicine',
    medibaseDesc: 'Brands, generics, and strengths map to one governed identity.',
    zoikoAvailScores: 'ZoikoAvail™ scores confidence',
    zoikoAvailDescSummary: 'Verified-pharmacy signals are weighted by freshness and reliability.',
    confirmBeforeVisiting: 'You confirm before visiting',
    confirmBeforeVisitingDesc: 'We show confidence, never exact stock. Always confirm with the pharmacy.',
    nearbyVerifiedPharmacies: 'NEARBY VERIFIED PHARMACIES',
    confidenceLabel: 'Confidence:',
    confidenceHigh: 'High',
    confidenceModerate: 'Moderate',
    confidenceLow: 'Low',
    featuredMedicines: 'FEATURED MEDICINES',
    recentSearchesCaps: 'RECENT SEARCHES',
    noNewSignals: 'No new signals for your saved medicines.',
    viewAll: 'View all',
    lastConfirmed: 'Last confirmed',
    checkAvailability: 'Check availability',
    confirmed: 'Confirmed',
    savedLocationCleared: 'Saved location cleared',
    of: 'of',
    pharmacies: 'pharmacies',
    new: 'new',
    isBackInStock: 'is back in stock',
    hasLimitedAvailability: 'has limited availability',
    isRunningLow: 'is running low',
    doesAvailabilityMeanInStock: 'Does availability mean the medicine is in stock?',
    disclaimerDetails: 'ZoikoMeds provides medicine availability intelligence only and does not guarantee that any medicine is in stock. Always confirm with the pharmacy before visiting.',
    confidenceUnknown: 'Unknown',
    medicineNotFound: 'Medicine not found',
    backToSearch: 'Back to search',
    generic: 'Generic',
    savedMedicine: 'Saved medicine',
    saveMedicine: 'Save medicine',
    findNearMe: 'Find near me',
    medicineInformation: 'Medicine information',
    brandName: 'Brand name',
    genericName: 'Generic name',
    strength: 'Strength',
    dosageForm: 'Dosage form',
    route: 'Route',
    manufacturer: 'Manufacturer',
    alsoSoldAs: 'Also sold as',
    category: 'Category',
    availabilityNow: 'Availability now',
    availablePharmacies: 'Available pharmacies',
    brandAlternatives: 'Brand alternatives',
    genericAlternatives: 'Generic alternatives',
    frequentlyAskedQuestions: 'Frequently asked questions',
    setDeliveryLocationTitle: 'Set your delivery location',
    deliveryLocationDesc: 'Enter a city, area, or 6-digit PIN code to check live medicine availability.',
    deliveryLocationPlaceholder: 'e.g. Austin, TX, Nizampet, or 500043',
    enterCityOrPinCode: 'Please enter a city, area, or 6-digit PIN code.',
    networkErrorVerifyingLocation: 'Network error verifying location. Please retry.',
    noMatchingLocationFound: 'No matching location found.',
    liveGeocodingSuggestions: 'Live Geocoding Suggestions',
    recentLocations: 'Recent locations:',
    cancel: 'Cancel',
    verifying: 'Verifying...',
    saveLocation: 'Save location',
    retry: 'Retry',
    contactDetailsDescSubtitle: 'Manage your contact details and account security.',
    validPhone: 'Please enter a valid phone number.',
    validIndianMobile: 'Please enter a valid Indian mobile number.',
    phoneTooShort: 'Phone number is too short.',
    phoneTooLong: 'Phone number is too long.',
    invalidPhoneCountry: 'Invalid phone number for the selected country.',
  },
  hi: {
    home: 'होम',
    searchMedicines: 'दवाइयां खोजें',
    howAvailabilityWorks: 'उपलब्धता प्रक्रिया',
    savedMedicines: 'सहेजी गई दवाएं',
    zoikoSignal: 'ज़ोइको सिग्नल™',
    notifications: 'सूचनाएं',
    myProfile: 'मेरी प्रोफाइल',
    settings: 'सेटिंग्स',
    helpSupport: 'सहायता एवं समर्थन',
    signOut: 'साइन आउट',
    myMedicines: 'मेरी दवाइयां',
    account: 'खाता',
    support: 'सहायता',
    findAvailability: 'अपने पास दवाओं की उपलब्धता खोजें',
    heroSubtitle: 'सत्यापित फार्मेसियों से रीयल-टाइम उपलब्धता देखने के लिए कोई भी दवा खोजें — मेडीबेस™ द्वारा संचालित।',
    searchPlaceholder: 'दवा का नाम, ब्रांड, या सॉल्ट खोजें...',
    scanPrescription: 'प्रिस्क्रिप्शन स्कैन करें',
    scanDesc: 'फोटो खींचें या अपलोड करें — हम दवाओं का नाम निकाल देंगे।',
    popularSearches: 'लोकप्रिय खोजें:',
    apply: 'लागू करें',
    languageUpdated: 'भाषा सफलतापूर्वक बदल दी गई',
    settingsSubtitle: 'भाषा, सुगमता और स्थान प्राथमिकताएं।',
    languageAndRegion: 'भाषा और क्षेत्र',
    chooseLanguage: 'अपनी पसंदीदा इंटरफ़ेस भाषा चुनें।',
    accessibility: 'सुगमता (Accessibility)',
    accessibilityDesc: 'इंटरफ़ेस को पढ़ने और उपयोग करने में आसान बनाएं।',
    largerText: 'बड़ा टेक्स्ट',
    largerTextDesc: 'लेबल और बॉडी टेक्स्ट का आकार बढ़ाएं।',
    reduceMotion: 'मोशन कम करें',
    reduceMotionDesc: 'एनिमेशन और ट्रांज़िशन को कम करें।',
    locationAndData: 'स्थान और डेटा',
    clearLocationDesc: 'इस डिवाइस पर सहेजे गए स्थान को हटाएं।',
    clearLocationBtn: 'सहेजा गया स्थान हटाएं',
    contactDetails: 'संपर्क विवरण',
    updateContactDesc: 'अपडेट करें कि सत्यापित फ़ार्मेसियां और ZoikoMeds आपसे कैसे संपर्क कर सकते हैं।',
    fullName: 'पूरा नाम',
    emailAddress: 'ईमेल पता',
    phone: 'फ़ोन',
    saveChanges: 'परिवर्तन सहेजें',
    password: 'पासवर्ड',
    updatePasswordDesc: 'अपना खाता पासवर्ड अपडेट करें।',
    currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नया पासवर्ड',
    confirmNewPassword: 'नए पासवर्ड की पुष्टि करें',
    updatePasswordBtn: 'पासवर्ड अपडेट करें',
    searchByName: 'नाम से खोजें',
    medicineName: 'दवा का नाम',
    searchArea: 'खोज क्षेत्र',
    useMyLocation: 'मेरे स्थान का उपयोग करें',
    usingCurrentLocation: 'आपके वर्तमान स्थान का उपयोग कर रहा है',
    locationSet: 'स्थान सेट किया गया',
    undo: 'पूर्ववत करें',
    searchAvailability: 'उपलब्धता खोजें',
    distanceFromMe: 'मुझसे दूरी:',
    km: 'कि.मी.',
    verifiedNetwork: 'सत्यापित फार्मेसी नेटवर्क',
    privacySafe: 'गोपनीयता-सुरक्षित खोज',
    noExactQuantities: 'कोई सटीक स्टॉक मात्रा नहीं',
    availabilityNearYou: 'आपके पास उपलब्धता',
    whatDoesConfidenceMean: 'विश्वास का क्या अर्थ है?',
    emptySearchPrompt: 'एक दवा दर्ज करें और यह देखने के लिए उपलब्धता खोजें पर टैप करें कि किन नजदीकी फार्मेसियों में इसके होने की संभावना है।',
    checkingAvailability: 'नजदीकी फार्मेसियों में उपलब्धता की जांच की जा रही है…',
    noPharmaciesFound: 'चयनित त्रिज्या के भीतर कोई फार्मेसी नहीं मिली। कोई भिन्न स्थान आज़माएं या दूरी बढ़ाएं।',
    directions: 'दिशा-निर्देश',
    callPharmacy: 'फार्मेसी को कॉल करें',
    save: 'सहेजें',
    saved: 'सहेजा गया',
    medicineNameHelp: 'केवल दवा का नाम दर्ज करें। लक्षण, निदान, बीमा विवरण या नुस्खे की छवियां दर्ज न करें।',
    searchAreaPlaceholder: 'शहर, पिन कोड या पोस्टकोड',
    addLocationHelp: 'आस-पास की फार्मेसियों को देखने के लिए स्थान जोड़ें।',
    understandingAvailability: 'उपलब्धता विश्वास को समझें',
    availabilitySubtitle: 'ZoikoMeds यह कैसे दिखाता है कि आपके पास दवा उपलब्ध होने की संभावना है — एक शासित विश्वास संकेत के रूप में।',
    whatIsZoikoAvail: 'ZoikoAvail™ क्या है?',
    whatIsZoikoAvailDesc: 'ZoikoAvail™ ZoikoMeds के पीछे का उपलब्धता विश्वास इंजन है। यह सत्यापित फार्मेसियों द्वारा साझा किए गए संकेतों को एक सरल विश्वास बैंड में बदलता है।',
    confidenceLevels: 'विश्वास का स्तर (Confidence Levels)',
    whyAvailabilityChanges: 'दवा की उपलब्धता क्यों बदलती है',
    howPharmaciesKeepCurrent: 'सत्यापित फ़ार्मेसियां इसे अद्यतन कैसे रखती हैं',
    verifiedPharmaciesOnly: 'केवल सत्यापित फ़ार्मेसियां',
    verifiedPharmaciesOnlyDesc: 'संकेत केवल उन फ़ार्मेसियों से आते हैं जिनके लाइसेंस सत्यापित हैं।',
    signalsNotStock: 'संकेत, स्टॉक संख्या नहीं',
    signalsNotStockDesc: 'फ़ार्मेसियां केवल उपलब्धता संकेत साझा करती हैं — हम सटीक मात्रा कभी उजागर नहीं करते।',
    freshnessWeighted: 'समय-भारित विश्वास',
    freshnessWeightedDesc: 'ZoikoAvail™ प्रत्येक संकेत को उसकी ताजगी और विश्वसनीयता के आधार पर तौलता है।',
    searchMedicineAvailability: 'दवा की उपलब्धता खोजें',
    likelyAvailableNow: 'अभी उपलब्ध होने की संभावना है',
    likelyAvailableNowDesc: 'एक सत्यापित फ़ार्मेसी ने हाल ही में संकेत दिया है कि यह दवा उपलब्ध होने की संभावना है।',
    mayBeLimited: 'सीमित हो सकती है — पहले पुष्टि करें',
    mayBeLimitedDesc: 'संकेत बताते हैं कि दवा उपलब्ध हो सकती है लेकिन सीमित हो सकती है। यात्रा से पहले पुष्टि करें।',
    notRecentlyConfirmed: 'हाल ही में पुष्टि नहीं की गई',
    notRecentlyConfirmedDesc: 'हाल ही में उपलब्धता की पुष्टि नहीं हुई है। अनिश्चित मानकर पहले कॉल करें।',
    noRecentSignal: 'कोई हालिया संकेत नहीं',
    noRecentSignalDesc: 'आस-पास की सत्यापित फ़ार्मेसियों से कोई हालिया संकेत नहीं मिला है।',
    search: 'खोजें',
    availability: 'उपलब्धता',
    savedMedicinesSubtitle: 'सत्यापित फ़ार्मेसियों में आपके द्वारा फॉलो की जाने वाली दवाओं की उपलब्धता ट्रैकिंग।',
    noSavedMedicinesYet: 'अभी तक कोई सहेजी गई दवाएं नहीं हैं',
    noSavedMedicinesDesc: 'अपनी उपलब्धता को ट्रैक करने के लिए खोज या विवरण पृष्ठ से एक दवा सहेजें।',
    alertsEnabled: 'अलर्ट सक्षम हैं',
    viewDetails: 'विवरण देखें',
    recentSearches: 'हालिया खोजें',
    verifiedPharmacies: 'सत्यापित फ़ार्मेसियां',
    activeAlerts: 'सक्रिय अलर्ट',
    yourZoikoSignal: 'आपका ज़ोइको सिग्नल™',
    zoikoSignalDesc: 'सहेजी गई दवाओं का स्टॉक कम होने या वापस आने पर अलर्ट प्राप्त करें।',
    savedMedicinesDesc: 'आपके द्वारा फॉलो की जाने वाली दवाओं की उपलब्धता ट्रैक करें।',
    feverPain: 'बुखार और दर्द',
    coldCough: 'सर्दी और खांसी',
    diabetes: 'डायबिटीज',
    heartBp: 'हृदय और बीपी',
    antibiotics: 'एंटीबायोटिक्स',
    acidity: 'एसिडिटी',
    allergy: 'एलर्जी',
    vitamins: 'विटामिन',
    homeDisclaimer: 'उपलब्धता एक शासित विश्वास संकेत है — सटीक स्टॉक नहीं। कृपया जाने से पहले फ़ार्मेसी से पुष्टि करें।',
    browseByHealthNeed: 'स्वास्थ्य आवश्यकता के अनुसार खोजें',
    zoikoSignalSubtitle: 'आपकी सहेजी गई दवाओं के लिए व्यक्तिगत उपलब्धता सूचनाएं।',
    liveMonitoring: 'लाइव निगरानी',
    markAllRead: 'सभी को पढ़ा हुआ चिन्हित करें',
    runningLow: 'स्टॉक कम हो रहा है',
    backInStockToday: 'आज पुनः स्टॉक में आया',
    allCaughtUp: 'आप पूरी तरह अपडेट हैं',
    noUrgentAlerts: 'आपकी सहेजी गई दवाओं के लिए अभी कोई जरूरी अलर्ट नहीं है।',
    mySavedMedicines: 'मेरी सहेजी गई दवाएं',
    searchSavedPlaceholder: 'सहेजी गई दवाओं में खोजें...',
    smartNotifications: 'स्मार्ट सूचनाएं',
    all: 'सभी',
    unread: 'अपठित',
    safetyAlerts: 'सुरक्षा अलर्ट',
    viewPharmacies: 'फ़ार्मेसियां देखें',
    markRead: 'पढ़ा गया चिन्हित करें',
    archive: 'आर्काइव करें',
    readAdvisory: 'सलाह पढ़ें',
    readAnnouncement: 'घोषणा पढ़ें',
    notificationsSubtitle: 'प्लेटफॉर्म अपडेट, दवा सुरक्षा अलर्ट, स्टॉक उपलब्धता सूचनाएं और सिस्टम संदेश।',
    announcements: 'घोषणाएं',
    stockAlerts: 'स्टॉक अलर्ट',
    safetyRecalls: 'सुरक्षा और रिकॉल',
    system: 'सिस्टम',
    noNotifications: 'कोई सूचनाएं नहीं हैं',
    notificationSettings: 'अधिसूचना सेटिंग्स',
    notificationSettingsDesc: 'चुनें कि ZoikoSignal™ आपको किस बारे में सूचित करता है — अलर्ट उपलब्धता विश्वास पर आधारित हैं।',
    availabilityAlerts: 'उपलब्धता अलर्ट',
    runningLowTitle: 'स्टॉक कम हो रहा है',
    runningLowDesc: 'मेरे पास सहेजी गई दवा का स्टॉक कम होने पर मुझे सूचित करें।',
    backInStockTitle: 'पुनः स्टॉक में आया',
    backInStockDesc: 'सहेजी गई दवा पुनः उपलब्ध होने पर मुझे सूचित करें।',
    nearbyRestockTitle: 'पास की रीस्टॉक',
    nearbyRestockDesc: 'पास की फ़ार्मेसी में नया स्टॉक आने पर मुझे सूचित करें।',
    safetyHeading: 'सुरक्षा',
    medicineRecallTitle: 'दवा रिकॉल अलर्ट',
    medicineRecallDesc: 'आपके द्वारा फॉलो की जाने वाली दवाओं के लिए रिकॉल नोटिस।',
    governmentSafetyTitle: 'सरकारी सुरक्षा अलर्ट',
    governmentSafetyDesc: 'आपकी सहेजी गई दवाओं की श्रेणियों के लिए राष्ट्रीय स्वास्थ्य सलाह।',
    channelsHeading: 'माध्यम (Channels)',
    pushNotificationsTitle: 'पुश नोटिफिकेशन',
    pushNotificationsDesc: 'इस डिवाइस पर अलर्ट प्राप्त करें।',
    emailNotificationsTitle: 'ईमेल नोटिफिकेशन',
    emailNotificationsDesc: 'ईमेल द्वारा सारांश प्राप्त करें।',
    smsNotificationsTitle: 'एसएमएस नोटिफिकेशन',
    smsNotificationsDesc: 'टेक्स्ट मैसेज द्वारा जरूरी अलर्ट प्राप्त करें।',
    whyChange1: 'फ़ार्मेसियां दिन भर स्टॉक वितरित करती हैं, इसलिए जो आज सुबह उपलब्ध था वह शाम तक उपलब्ध नहीं भी हो सकता है।',
    whyChange2: 'प्रत्येक फ़ार्मेसी के लिए नई डिलीवरी और रीस्टॉक अलग-अलग समय सारणी पर आते हैं।',
    whyChange3: 'क्षेत्रीय मांग और आपूर्ति का दबाव (जैसे मौसमी बीमारियां) उपलब्धता को तेजी से बदलता है।',
    whyChange4: 'संकेत की समय-सीमा: फ़ार्मेसी द्वारा अंतिम पुष्टि किए गए समय जितना अधिक होगा, हमारा विश्वास उतना ही कम होगा।',
    confirmNote: 'उपलब्धता का अर्थ यह नहीं है कि दवा आपके लिए आरक्षित है। यात्रा करने से पहले हमेशा फ़ार्मेसी पर कॉल करें या जाएं।',
    scopeNote: 'केवल उपलब्धता संबंधी जानकारी — कोई स्टॉक संख्या, स्टॉक आरक्षण या ऑनलाइन बिक्री नहीं।',
    verifiedAccount: 'सत्यापित खाता',
    readOnly: 'केवल पढ़ने योग्य',
    emailReadOnlyNotice: 'ईमेल आपके लॉगिन खाते से जुड़ा हुआ है और इसे बदला नहीं जा सकता।',
    profilePrivacyNotice: 'ZoikoMeds नुस्खे या स्वास्थ्य रिकॉर्ड एकत्र नहीं करता है। हम केवल वही संपर्क विवरण सहेजते हैं जो आप अलर्ट के लिए प्रदान करते हैं।',
    profileUpdated: 'प्रोफाइल अपडेट हो गई',
    passwordUpdated: 'पासवर्ड अपडेट हो गया',
    enterPassword: 'पासवर्ड दर्ज करें',
    passwordMinLength: 'पासवर्ड कम से कम 8 अक्षरों का होना चाहिए।',
    passwordsDoNotMatch: 'पासवर्ड मेल नहीं खाते।',
    dropPrescriptionHere: 'अपना प्रिस्क्रिप्शन यहां डालें',
    extractMedicineDesc: 'हम दवाओं के नाम निकाल लेंगे — आप चुनें कि किसे खोजना है। आपकी छवि कभी सहेजी या साझा नहीं की जाती है।',
    browseFile: 'फ़ाइल चुनें',
    maxFileNotice: 'JPG, PNG, PDF, HEIC — अधिकतम 10 MB',
    or: 'या',
    takePhoto: 'फ़ोटो लें',
    fromGallery: 'गैलरी से',
    privacyNoticeTitle: 'गोपनीयता सूचना:',
    prescriptionPrivacyNotice: 'आपकी प्रिस्क्रिप्शन छवि का उपयोग केवल इस खोज के लिए दवाओं के नाम निकालने के लिए किया जाता है। इसे कभी भी सहेजा, साझा या आपकी पहचान के लिए उपयोग नहीं किया जाता है। ZoikoMeds प्रिस्क्रिप्शन को प्रोसेस या वैलिडेट नहीं करता है। कोई चिकित्सा सलाह प्रदान नहीं की जाती है।',
    yourLocationForNearbySearch: 'आपका स्थान (पास की खोज के लिए)',
    useMyCurrentLocation: 'मेरे वर्तमान स्थान का उपयोग करें',
    medicinesFound: 'दवाएं मिलीं',
    scanAnother: 'दूसरा स्कैन करें',
    chooseMedicinesToSearch: 'चुनें कि अपने आस-पास उपलब्धता के लिए किन दवाओं की खोज करनी है।',
    extractedNamesNotice: 'निकाले गए नाम केवल आपकी छवि से पढ़े गए हैं। अपने नुस्खे के साथ सटीक दवा की पुष्टि करें।',
    readingPrescription: 'आपका प्रिस्क्रिप्शन पढ़ा जा रहा है…',
    extractingNamesFrom: 'दवाओं के नाम निकाले जा रहे हैं',
    deviceOnlyNotice: 'यह आपके डिवाइस पर होता है — छवि अपलोड नहीं की जाती है।',
    prescription: 'प्रिस्क्रिप्शन',
    otc: 'ओटीसी (OTC)',
    governedIdentityNotice: 'शासित दवा पहचान — मेडीबेस™। नीचे दी गई उपलब्धता एक विश्वास संकेत है, सटीक स्टॉक नहीं।',
    requiresConfirmation: 'पुष्टि की आवश्यकता है — जाने से पहले कॉल करें।',
    distance: 'दूरी',
    signalUpdated: 'सिग्नल अद्यतन',
    call: 'कॉल करें',
    morePharmaciesWeb: 'आपके आस-पास की और फ़ार्मेसियां (वेब से)',
    openNow: 'अभी खुला है',
    closed: 'बंद है',
    rating: 'रेटिंग',
    webPharmaciesDisclaimer: 'स्थान के आधार पर वेब पर मिली और ZoikoMeds सत्यापित नेटवर्क से बाहर। स्टॉक की पुष्टि नहीं है — कृपया पहले कॉल करें।',
    howAvailabilityWorksCaps: 'उपलब्धता कैसे काम करती है',
    medibaseIdentifies: 'MediBase™ दवा की पहचान करता है',
    medibaseDesc: 'ब्रांड, जेनेरिक और ताकत एक शासित पहचान में मैप होते हैं।',
    zoikoAvailScores: 'ZoikoAvail™ विश्वास स्कोर करता है',
    zoikoAvailDescSummary: 'सत्यापित-फ़ार्मेसी संकेतों को ताजगी और विश्वसनीयता द्वारा तौला जाता है।',
    confirmBeforeVisiting: 'जाने से पहले पुष्टि करें',
    confirmBeforeVisitingDesc: 'हम विश्वास दिखाते हैं, सटीक स्टॉक कभी नहीं। हमेशा फ़ार्मेसी से पुष्टि करें।',
    nearbyVerifiedPharmacies: 'आस-पास की सत्यापित फ़ार्मेसियां',
    confidenceLabel: 'विश्वास:',
    confidenceHigh: 'उच्च',
    confidenceModerate: 'मध्यम',
    confidenceLow: 'कम',
    featuredMedicines: 'प्रमुख दवाएं',
    recentSearchesCaps: 'हालिया खोजें',
    noNewSignals: 'आपकी सहेजी गई दवाओं के लिए कोई नया संकेत नहीं है।',
    viewAll: 'सभी देखें',
    lastConfirmed: 'अंतिम पुष्टि',
    checkAvailability: 'उपलब्धता जांचें',
    confirmed: 'पुष्टि की गई',
    savedLocationCleared: 'सहेजा गया स्थान हटा दिया गया',
    of: 'का',
    pharmacies: 'फ़ार्मेसियां',
    new: 'नया',
    isBackInStock: 'पुनः स्टॉक में आ गया है',
    hasLimitedAvailability: 'सीमित उपलब्धता है',
    isRunningLow: 'का स्टॉक कम हो रहा है',
    doesAvailabilityMeanInStock: 'क्या उपलब्धता का अर्थ है कि दवा स्टॉक में है?',
    disclaimerDetails: 'ZoikoMeds केवल दवा उपलब्धता की जानकारी प्रदान करता है और स्टॉक की गारंटी नहीं देता है। जाने से पहले हमेशा फ़ार्मेसी से पुष्टि करें।',
    confidenceUnknown: 'अज्ञात',
    medicineNotFound: 'दवा नहीं मिली',
    backToSearch: 'खोज पर वापस जाएं',
    generic: 'जेनेरिक',
    savedMedicine: 'सहेजी गई दवा',
    saveMedicine: 'दवा सहेजें',
    findNearMe: 'मेरे पास खोजें',
    medicineInformation: 'दवा की जानकारी',
    brandName: 'ब्रांड का नाम',
    genericName: 'जेनेरिक नाम',
    strength: 'ताकत (Strength)',
    dosageForm: 'खुराक का रूप (Form)',
    route: 'मार्ग (Route)',
    manufacturer: 'निर्माता',
    alsoSoldAs: 'अन्य ब्रांड नाम',
    category: 'श्रेणी',
    availabilityNow: 'वर्तमान उपलब्धता',
    availablePharmacies: 'उपलब्ध फ़ार्मेसियां',
    brandAlternatives: 'ब्रांड विकल्प',
    genericAlternatives: 'जेनेरिक विकल्प',
    frequentlyAskedQuestions: 'अक्सर पूछे जाने वाले प्रश्न',
    setDeliveryLocationTitle: 'अपनी डिलीवरी का स्थान सेट करें',
    deliveryLocationDesc: 'लाइव दवा उपलब्धता की जांच के लिए शहर, क्षेत्र या 6-अंकीय पिन कोड दर्ज करें।',
    deliveryLocationPlaceholder: 'उदा. जयपुर, निजामपेट, या 500043',
    enterCityOrPinCode: 'कृपया शहर, क्षेत्र या 6-अंकीय पिन कोड दर्ज करें।',
    networkErrorVerifyingLocation: 'स्थान सत्यापन में नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।',
    noMatchingLocationFound: 'कोई मेल खाता स्थान नहीं मिला।',
    liveGeocodingSuggestions: 'लाइव स्थान सुझाव',
    recentLocations: 'हाल के स्थान:',
    cancel: 'रद्द करें',
    verifying: 'सत्यापित किया जा रहा है...',
    saveLocation: 'स्थान सहेजें',
    retry: 'पुनः प्रयास करें',
    contactDetailsDescSubtitle: 'अपने संपर्क विवरण और खाता सुरक्षा का प्रबंधन करें।',
    validPhone: 'कृपया एक वैध फ़ोन नंबर दर्ज करें।',
    validIndianMobile: 'कृपया एक वैध भारतीय मोबाइल नंबर दर्ज करें।',
    phoneTooShort: 'फ़ोन नंबर बहुत छोटा है।',
    phoneTooLong: 'फ़ोन नंबर बहुत लंबा है।',
    invalidPhoneCountry: 'चयनित देश के लिए अमान्य फ़ोन नंबर।',
  },
  te: {
    home: 'హోమ్',
    searchMedicines: 'మందుల శోధన',
    howAvailabilityWorks: 'లభ్యత ప్రక్రియ',
    savedMedicines: 'సేవ్ చేసిన మందులు',
    zoikoSignal: 'జోయికో సిగ్నల్™',
    notifications: 'నోటిఫికేషన్లు',
    myProfile: 'నా ప్రొఫైల్',
    settings: 'సెట్టింగ్‌లు',
    helpSupport: 'సహాయం & మద్దతు',
    signOut: 'సైన్ అవుట్',
    myMedicines: 'నా మందులు',
    account: 'ఖాతా',
    support: 'సహాయం',
    findAvailability: 'మీ సమీపంలో మందుల లభ్యతను శోధించండి',
    heroSubtitle: 'తనిఖీ చేయబడిన ఫార్మసీల నుండి నిజ-సమయ లభ్యత సమాచారాన్ని చూడటానికి శోధించండి.',
    searchPlaceholder: 'మందు పేరు లేదా బ్రాండ్ నమోదు చేయండి...',
    scanPrescription: 'ప్రిస్క్రిప్షన్ స్కాన్ చేయండి',
    scanDesc: 'ఫోటో లేదా ఫైల్ అప్‌లోడ్ చేయండి — మేము వివరాలు తీస్తాము.',
    popularSearches: 'ప్రజాదరణ పొందినవి:',
    apply: 'వర్తింపజేయి',
    languageUpdated: 'భాష విజయవంతంగా మార్చబడింది',
    settingsSubtitle: 'భాష, యాక్సెసిబిలిటీ మరియు స్థాన ప్రాధాన్యతలు.',
    languageAndRegion: 'భాష & ప్రాంతం',
    chooseLanguage: 'మీకు కావలసిన భాషను ఎంచుకోండి.',
    accessibility: 'యాక్సెసిబిలిటీ (Accessibility)',
    accessibilityDesc: 'ఇంటర్‌ఫేస్‌ను చదవడానికి మరియు ఉపయోగించడానికి సులభతరం చేయండి.',
    largerText: 'పెద్ద అక్షరాలు',
    largerTextDesc: 'అక్షరాల పరిమాణాన్ని పెంచండి.',
    reduceMotion: 'మోషన్ తగ్గించండి',
    reduceMotionDesc: 'యానిమేషన్లను తగ్గించండి.',
    locationAndData: 'స్థానం & డేటా',
    clearLocationDesc: 'ఈ పరికరంలో సేవ్ చేసిన స్థానాన్ని తొలగించండి.',
    clearLocationBtn: 'సేవ్ చేసిన స్థానాన్ని తొలగించు',
    contactDetails: 'సంప్రదింపు వివరాలు',
    updateContactDesc: 'మిమ్మల్ని సంప్రదించడానికి వివరాలను నవీకరించండి.',
    fullName: 'పూర్తి పేరు',
    emailAddress: 'ఈమెయిల్ చిరునామా',
    phone: 'ఫోన్ సంఖ్య',
    saveChanges: 'మార్పులను సేవ్ చేయి',
    password: 'పాస్‌వర్డ్',
    updatePasswordDesc: 'మీ ఖాతా పాస్‌వర్డ్‌ను నవీకరించండి.',
    currentPassword: 'ప్రస్తుత పాస్‌వర్డ్',
    newPassword: 'కొత్త పాస్‌వర్డ్',
    confirmNewPassword: 'కొత్త పాస్‌వర్డ్‌ను ధృవీకరించండి',
    updatePasswordBtn: 'పాస్‌వర్డ్ నవీకరించు',
    searchByName: 'పేరు ద్వారా శోధించండి',
    medicineName: 'మందు పేరు',
    searchArea: 'శోధన ప్రాంతం',
    useMyLocation: 'నా స్థానాన్ని ఉపయోగించు',
    usingCurrentLocation: 'మీ ప్రస్తుత స్థానాన్ని ఉపయోగిస్తోంది',
    locationSet: 'స్థానం సెట్ చేయబడింది',
    undo: 'రద్దు చేయి',
    searchAvailability: 'లభ్యత శోధించండి',
    distanceFromMe: 'నా నుండి దూరం:',
    km: 'కి.మీ.',
    verifiedNetwork: 'ప్రామాణీకరించబడిన ఫార్మసీ నెట్‌వర్క్',
    privacySafe: 'గోప్యతా-సురక్షిత శోధన',
    noExactQuantities: 'కచ్చితమైన నిల్వ పరిమాణాలు లేవు',
    availabilityNearYou: 'మీ సమీపంలో లభ్యత',
    whatDoesConfidenceMean: 'విశ్వసనీయత అంటే ఏమిటి?',
    emptySearchPrompt: 'ఒక మందును నమోదు చేసి, సమీపంలోని ఏ ఫార్మసీలలో అది ఉండవచ్చో చూడటానికి లభ్యత శోధించండి నొక్కండి.',
    checkingAvailability: 'సమీపంలోని ఫార్మసీలలో లభ్యతను తనిఖీ చేస్తోంది…',
    noPharmaciesFound: 'ఎంచుకున్న పరిధిలో ఫార్మసీలు ఏవీ కనుగొనబడలేదు. విభిన్న స్థానాన్ని ప్రయత్నించండి లేదా దూరాన్ని పెంచండి.',
    directions: 'దిశలు',
    callPharmacy: 'ఫార్మసీకి కాల్ చేయండి',
    save: 'సేవ్ చేయి',
    saved: 'సేవ్ చేయబడింది',
    medicineNameHelp: 'మందు పేరు మాత్రమే నమోదు చేయండి. లక్షణాలు, భీమా వివరాలు లేదా ప్రిస్క్రిప్షన్ చిత్రాలను నమోదు చేయవద్దు.',
    searchAreaPlaceholder: 'నగరం, పిన్ కోడ్ లేదా పోస్ట్‌కోడ్',
    addLocationHelp: 'సమీపంలోని ఫార్మసీలను చూడటానికి ఒక స్థానాన్ని జోడించండి.',
    understandingAvailability: 'లభ్యత విశ్వసనీయతను అర్థం చేసుకోవడం',
    availabilitySubtitle: 'మీ సమీపంలో మందులు లభించే అవకాశం ఉందో లేదో ZoikoMeds చూపిస్తుంది.',
    whatIsZoikoAvail: 'ZoikoAvail™ అంటే ఏమిటి?',
    whatIsZoikoAvailDesc: 'ZoikoAvail™ అనేది తనిఖీ చేసిన ఫార్మసీల నుండి సమాచారాన్ని విశ్వసనీయ స్థాయిలుగా మారుస్తుంది.',
    confidenceLevels: 'విశ్వసనీయత స్థాయిలు',
    whyAvailabilityChanges: 'మందుల లభ్యత ఎందుకు మారుతుంది',
    howPharmaciesKeepCurrent: 'తనిఖీ చేసిన ఫార్మసీలు దీనిని ఎలా అప్‌డేట్ చేస్తాయి',
    verifiedPharmaciesOnly: 'ప్రామాణీకరించబడిన ఫార్మసీలు మాత్రమే',
    verifiedPharmaciesOnlyDesc: 'లైసెన్స్ తనిఖీ చేయబడిన ఫార్మసీల నుండి మాత్రమే సంకేతాలు వస్తాయి.',
    signalsNotStock: 'సంకేతాలు మాత్రమే, నిల్వలు కాదు',
    signalsNotStockDesc: 'కచ్చితమైన నిల్వల సంఖ్యను ఎప్పుడూ చూపించము.',
    freshnessWeighted: 'తాజా సమాచార ఆధారితం',
    freshnessWeightedDesc: 'ఇటీవలి సమాచారాన్ని బట్టి విశ్వసనీయత స్థాయిని లెక్కిస్తుంది.',
    searchMedicineAvailability: 'మందుల లభ్యత శోధించండి',
    likelyAvailableNow: 'ఇప్పుడు లభించే అవకాశం ఉంది',
    likelyAvailableNowDesc: 'సమీపంలోని ఫార్మసీ నుండి ఇటీవల సమాచారం అందింది.',
    mayBeLimited: 'పరిమితంగా ఉండవచ్చు — ముందుగా నిర్ధారించుకోండి',
    mayBeLimitedDesc: 'ప్రయాణించే ముందు ఫార్మసీని సంప్రదించండి.',
    notRecentlyConfirmed: 'ఇటీవల ధృవీకరించబడలేదు',
    notRecentlyConfirmedDesc: 'ముందుగా కాల్ చేసి సమాచారం తెలుసుకోండి.',
    noRecentSignal: 'ఇటీవలి సమాచారం లేదు',
    noRecentSignalDesc: 'సమీపంలోని ఫార్మసీల నుండి ఇటీవల సంకేతాలు లేవు.',
    search: 'శోధన',
    availability: 'లభ్యత',
    savedMedicinesSubtitle: 'మీరు అనుసరించే మందుల లభ్యత వివరాలను ఇక్కడ ట్రాక్ చేయండి.',
    noSavedMedicinesYet: 'ఇంకా సేవ్ చేసిన మందులు లేవు',
    noSavedMedicinesDesc: 'ఒక మందును సేవ్ చేయండి.',
    alertsEnabled: 'అలర్టులు ప్రారంభించబడ్డాయి',
    viewDetails: 'వివరాలు చూడండి',
    recentSearches: 'ఇటీవలి శోధనలు',
    verifiedPharmacies: 'తనిఖీ చేసిన ఫార్మసీలు',
    activeAlerts: 'యాక్టివ్ అలర్టులు',
    yourZoikoSignal: 'మీ జోయికో సిగ్నల్™',
    zoikoSignalDesc: 'సేవ్ చేసిన మందుల నిల్వలు తగ్గినప్పుడు సమాచారం పొందండి.',
    savedMedicinesDesc: 'మందుల లభ్యతను ఇక్కడ ట్రాక్ చేయండి.',
    feverPain: 'జ్వరం & నొప్పులు',
    coldCough: 'జలుబు & దగ్గు',
    diabetes: 'డయాబెటిస్',
    heartBp: 'గుండె & బిపి',
    antibiotics: 'యాంటీబయోటిక్స్',
    acidity: 'ఎసిడిటీ',
    allergy: 'అలెర్జీ',
    vitamins: 'విటమిన్లు',
    homeDisclaimer: 'లభ్యత అనేది సమాచారం మాత్రమే — నిల్వ గ్యారెంటీ కాదు.',
    browseByHealthNeed: 'ఆరోగ్య అవసరాల ఆధారంగా శోధించండి',
    zoikoSignalSubtitle: 'మీ సేవ్ చేసిన మందుల కోసం ప్రత్యక్ష సమాచారం.',
    liveMonitoring: 'ప్రత్యక్ష పరిశీలన',
    markAllRead: 'అన్నింటినీ చదివినట్లు గుర్తించు',
    runningLow: 'నిల్వలు తగ్గుతున్నాయి',
    backInStockToday: 'ఈ రోజు మళ్లీ అందుబాటులోకి వచ్చింది',
    allCaughtUp: 'మీరు అప్‌డేట్‌గా ఉన్నారు',
    noUrgentAlerts: 'ప్రస్తుతం అత్యవసర అలర్టులు లేవు.',
    mySavedMedicines: 'నా సేవ్ చేసిన మందులు',
    searchSavedPlaceholder: 'సేవ్ చేసిన మందులలో శోధించండి...',
    smartNotifications: 'స్మార్ట్ నోటిఫికేషన్లు',
    all: 'అన్నీ',
    unread: 'చదవనివి',
    safetyAlerts: 'రక్షణ అలర్టులు',
    viewPharmacies: 'ఫార్మసీలను చూడండి',
    markRead: 'చదివినట్లు గుర్తించు',
    archive: 'ఆర్కైవ్ చేయి',
    readAdvisory: 'సూచన చదవండి',
    readAnnouncement: 'ప్రకటన చదవండి',
    notificationsSubtitle: 'ప్లాట్‌ఫారమ్ నవీకరణలు మరియు సమాచారం.',
    announcements: 'ప్రకటనలు',
    stockAlerts: 'స్టాక్ అలర్టులు',
    safetyRecalls: 'భద్రతా హెచ్చరికలు',
    system: 'సిస్టమ్',
    noNotifications: 'నోటిఫికేషన్లు లేవు',
    notificationSettings: 'నోటిఫికేషన్ సెట్టింగ్‌లు',
    notificationSettingsDesc: 'ZoikoSignal™ మీకు దేని గురించి సమాచారం అందించాలో ఎంచుకోండి.',
    availabilityAlerts: 'లభ్యత అలర్టులు',
    runningLowTitle: 'నిల్వలు తగ్గుతున్నాయి',
    runningLowDesc: 'సమీపంలో మందుల నిల్వలు తగ్గినప్పుడు నాకు సమాచారం ఇవ్వండి.',
    backInStockTitle: 'మళ్లీ అందుబాటులోకి వచ్చింది',
    backInStockDesc: 'సేవ్ చేసిన మందులు మళ్లీ అందుబాటులోకి వచ్చినప్పుడు సమాచారం ఇవ్వండి.',
    nearbyRestockTitle: 'సమీప ఫార్మసీల నవీకరణ',
    nearbyRestockDesc: 'సమీపంలోని ఫార్మసీకి కొత్త నిల్వలు వచ్చినప్పుడు సమాచారం ఇవ్వండి.',
    safetyHeading: 'భద్రత',
    medicineRecallTitle: 'మందుల రీకాల్ అలర్టులు',
    medicineRecallDesc: 'మీరు అనుసరించే మందుల నిలిపివేత ప్రకటనలు.',
    governmentSafetyTitle: 'ప్రభుత్వ రక్షణ అలర్టులు',
    governmentSafetyDesc: 'మీ సేవ్ చేసిన మందుల రకాలకు సంబంధించిన జాతీయ ఆరోగ్య హెచ్చరికలు.',
    channelsHeading: 'మాధ్యమాలు',
    pushNotificationsTitle: 'పుష్ నోటిఫికేషన్లు',
    pushNotificationsDesc: 'ఈ పరికరంలో అలర్టులను పొందండి.',
    emailNotificationsTitle: 'ఈమెయిల్ నోటిఫికేషన్లు',
    emailNotificationsDesc: 'ఈమెయిల్ ద్వారా సారాంశాన్ని పొందండి.',
    smsNotificationsTitle: 'SMS నోటిఫికేషన్లు',
    smsNotificationsDesc: 'మెసేజ్ ద్వారా అత్యవసర అలర్టులను పొందండి.',
    whyChange1: 'ఫార్మసీలు రోజంతా మందులను అందిస్తాయి, కాబట్టి ఉదయం అందుబాటులో ఉన్నది సాయంత్రానికి లేకపోవచ్చు.',
    whyChange2: 'ప్రతి ఫార్మసీకి కొత్త సరఫరా మరియు రీస్టాక్ వేర్వేరు సమయాల్లో వస్తాయి.',
    whyChange3: 'ప్రాంతీయ అవసరాలు మరియు సరఫరా ప్రభావం వల్ల లభ్యత వేగంగా మారుతుంది.',
    whyChange4: 'సమాచారం పాతబడే కొద్దీ విశ్వసనీయత స్థాయి తగ్గుతుంది.',
    confirmNote: 'లభ్యత అనేది తనిఖీ చేయబడిన ఫార్మసీల నుండి వచ్చిన సమాచారం — ఖచ్చితమైన నిల్వ కాదు. వెళ్ళే ముందు ఫార్మసీని సంప్రదించండి.',
    scopeNote: 'ZoikoMeds లభ్యత సమాచారాన్ని మాత్రమే అందిస్తుంది.',
    verifiedAccount: 'ధృవీకరించబడిన ఖాతా',
    readOnly: 'చదవడానికి మాత్రమే',
    emailReadOnlyNotice: 'ఈమెయిల్ మీ లాగిన్ ఖాతాకు లింక్ చేయబడింది మరియు మార్చలేరు.',
    profilePrivacyNotice: 'ZoikoMeds మీ హెల్త్ రికార్డులను సేకరించదు.',
    profileUpdated: 'ప్రొఫైల్ నవీకరించబడింది',
    passwordUpdated: 'పాస్‌వర్డ్ నవీకరించబడింది',
    enterPassword: 'పాస్‌వర్డ్ నమోదు చేయండి',
    passwordMinLength: 'పాస్‌వర్డ్ కనీసం 8 అక్షరాలు ఉండాలి.',
    passwordsDoNotMatch: 'పాస్‌వర్డ్‌లు సరిపోలలేదు.',
    dropPrescriptionHere: 'మీ ప్రిస్క్రిప్షన్‌ను ఇక్కడ వేయండి',
    extractMedicineDesc: 'మేము మందుల పేర్లను సేకరిస్తాము — దేనిని వెతకాలో మీరు ఎంచుకోండి.',
    browseFile: 'ఫైల్ ఎంచుకోండి',
    maxFileNotice: 'JPG, PNG, PDF, HEIC — గరిష్టంగా 10 MB',
    or: 'లేదా',
    takePhoto: 'ఫోటో తీయండి',
    fromGallery: 'గ్యాలరీ నుండి',
    privacyNoticeTitle: 'గోప్యతా నోటీసు:',
    prescriptionPrivacyNotice: 'మీ ప్రిస్క్రిప్షన్ చిత్రం శోధన కోసం మాత్రమే ఉపయోగించబడుతుంది.',
    yourLocationForNearbySearch: 'మీ ప్రాంతం (సమీప శోధన కోసం)',
    useMyCurrentLocation: 'నా ప్రస్తుత స్థానాన్ని ఉపయోగించు',
    medicinesFound: 'మందులు కనుగొనబడ్డాయి',
    scanAnother: 'మరొకటి స్కాన్ చేయండి',
    chooseMedicinesToSearch: 'సమీపంలో లభ్యత కోసం శోధించాల్సిన మందులను ఎంచుకోండి.',
    extractedNamesNotice: 'కనుగొనబడిన పేర్లు మీ చిత్రం నుండి చదవబడ్డాయి.',
    readingPrescription: 'ప్రిస్క్రిప్షన్ చదవబడుతోంది…',
    extractingNamesFrom: 'మందుల పేర్లు తీయబడుతున్నాయి',
    deviceOnlyNotice: 'ఇది మీ పరికరంలో మాత్రమే జరుగుతుంది.',
    prescription: 'ప్రిస్క్రిప్షన్',
    otc: 'ఓటీసీ (OTC)',
    governedIdentityNotice: 'MediBase™ మందుల గుర్తింపు. లభ్యత అనేది సమాచారం మాత్రమే.',
    requiresConfirmation: 'నిర్ధారణ అవసరం — వెళ్ళే ముందు కాల్ చేయండి.',
    distance: 'దూరం',
    signalUpdated: 'సిగ్నల్ నవీకరించబడింది',
    call: 'కాల్ చేయండి',
    morePharmaciesWeb: 'మీ సమీపంలో మరిన్ని ఫార్మసీలు (వెబ్ నుండి)',
    openNow: 'ఇప్పుడు తెరిచి ఉంది',
    closed: 'మూసివేయబడింది',
    rating: 'రేటింగ్',
    webPharmaciesDisclaimer: 'వెబ్‌లో కనుగొనబడిన ఫార్మసీలు. దయచేసి ముందుగా కాల్ చేయండి.',
    howAvailabilityWorksCaps: 'లభ్యత ఎలా పనిచేస్తుంది',
    medibaseIdentifies: 'MediBase™ మందును గుర్తిస్తుంది',
    medibaseDesc: 'బ్రాండ్లు మరియు జెనెరిక్‌లు ఒకే గుర్తింపునకు మ్యాప్ చేయబడతాయి.',
    zoikoAvailScores: 'ZoikoAvail™ లభ్యతను విశ్లేషిస్తుంది',
    zoikoAvailDescSummary: 'ఫార్మసీ సమాచారం ఆధారంగా విశ్లేషించబడుతుంది.',
    confirmBeforeVisiting: 'వెళ్ళే ముందు నిర్ధారించుకోండి',
    confirmBeforeVisitingDesc: 'ఎల్లప్పుడూ ఫార్మసీతో నిర్ధారించుకోండి.',
    nearbyVerifiedPharmacies: 'సమీపంలో తనిఖీ చేయబడిన ఫార్మసీలు',
    confidenceLabel: 'నమ్మకం:',
    confidenceHigh: 'అధికం',
    confidenceModerate: 'మధ్యస్థం',
    confidenceLow: 'తక్కువ',
    featuredMedicines: 'ముఖ్యమైన మందులు',
    recentSearchesCaps: 'ఇటీవలి శోధనలు',
    noNewSignals: 'మీ సేవ్‌ చేసిన మందులకు కొత్త నోటిఫికేషన్లు లేవు.',
    viewAll: 'అన్నీ చూడండి',
    lastConfirmed: 'చివరి నిర్ధారణ',
    checkAvailability: 'లభ్యతను తనిఖీ చేయండి',
    confirmed: 'నిర్ధారించబడింది',
    savedLocationCleared: 'సేవ్ చేసిన స్థానం తీసివేయబడింది',
    of: 'లో',
    pharmacies: 'ఫార్మసీలు',
    new: 'కొత్త',
    isBackInStock: 'మళ్ళీ స్టాక్‌లోకి వచ్చింది',
    hasLimitedAvailability: 'పరిమిత లభ్యత ఉంది',
    isRunningLow: 'స్టాక్ తగ్గుతోంది',
    doesAvailabilityMeanInStock: 'లభ్యత అంటే మందు నిల్వ ఉందనా?',
    disclaimerDetails: 'ZoikoMeds లభ్యత సమాచారాన్ని మాత్రమే అందిస్తుంది.',
    confidenceUnknown: 'తెలియదు',
    medicineNotFound: 'మందు కనుగొనబడలేదు',
    backToSearch: 'శోధనకు తిరిగి వెళ్ళు',
    generic: 'జెనెరిక్',
    savedMedicine: 'సేవ్ చేసిన మందు',
    saveMedicine: 'మందును సేవ్ చేయి',
    findNearMe: 'నా సమీపంలో వెతకండి',
    medicineInformation: 'మందు సమాచారం',
    brandName: 'బ్రాండ్ పేరు',
    genericName: 'జెనెరిక్ పేరు',
    strength: 'సామర్థ్యం',
    dosageForm: 'రూపం',
    route: 'మార్గం',
    manufacturer: 'తయారీదారు',
    alsoSoldAs: 'ఇతర పేర్లు',
    category: 'వర్గం',
    availabilityNow: 'ప్రస్తుత లభ్యత',
    availablePharmacies: 'లభ్యత ఉన్న ఫార్మసీలు',
    brandAlternatives: 'బ్రాండ్ ప్రత్యామ్నాయాలు',
    genericAlternatives: 'జెనెరిక్ ప్రత్యామ్నాయాలు',
    frequentlyAskedQuestions: 'తరచుగా అడిగే ప్రశ్నలు',
    setDeliveryLocationTitle: 'మీ డెలివరీ స్థానాన్ని ఎంచుకోండి',
    deliveryLocationDesc: 'లైవ్ ఔషధ లభ్యతను తనిఖీ చేయడానికి నగరం, ప్రాంతం లేదా 6-అంకెల పిన్ కోడ్‌ను నమోదు చేయండి.',
    deliveryLocationPlaceholder: 'ఉదా. హైదరాబాదు, నిజాంపేట్, లేదా 500043',
    enterCityOrPinCode: 'దయచేసి నగరం, ప్రాంతం లేదా 6-అంకెల పిన్ కోడ్‌ను నమోదు చేయండి.',
    networkErrorVerifyingLocation: 'స్థానాన్ని పరిశీలించడంలో నెట్‌వర్క్ లోపం. దయచేసి మళ్లీ ప్రయత్నించండి.',
    noMatchingLocationFound: 'సరిపోలే స్థానం కనుగొనబడలేదు.',
    liveGeocodingSuggestions: 'లైవ్ ప్రాంతపు సూచనలు',
    recentLocations: 'ఇటీవలి స్థానాలు:',
    cancel: 'రద్దు చేయి',
    verifying: 'పరిశీలిస్తోంది...',
    saveLocation: 'స్థానాన్ని సేవ్ చేయి',
    retry: 'మళ్లీ ప్రయత్నించండి',
    contactDetailsDescSubtitle: 'మీ సంప్రదింపు వివరాలు మరియు ఖాతా భద్రతను నిర్వహించండి.',
    validPhone: 'దయచేసి చెల్లుబాటు అయ్యే ఫోన్ నంబర్‌ను నమోదు చేయండి.',
    validIndianMobile: 'దయచేసి చెల్లుబాటు అయ్యే భారతీయ మొబైల్ నంబర్‌ను నమోదు చేయండి.',
    phoneTooShort: 'ఫోన్ నంబర్ చాలా చిన్నదిగా ఉంది.',
    phoneTooLong: 'ఫోన్ నంబర్ చాలా పొడవుగా ఉంది.',
    invalidPhoneCountry: 'ఎంచుకున్న దేశానికి ఫోన్ నంబర్ చెల్లదు.',
  },
  es: {
    home: 'Inicio',
    searchMedicines: 'Buscar Medicamentos',
    howAvailabilityWorks: 'Cómo funciona la disponibilidad',
    savedMedicines: 'Medicamentos Guardados',
    zoikoSignal: 'ZoikoSignal™',
    notifications: 'Notificaciones',
    myProfile: 'Mi Perfil',
    settings: 'Configuración',
    helpSupport: 'Ayuda y Soporte',
    signOut: 'Cerrar Sesión',
    myMedicines: 'Mis Medicamentos',
    account: 'Cuenta',
    support: 'Soporte',
    findAvailability: 'Busque disponibilidad de medicamentos cerca de usted',
    heroSubtitle: 'Busque un medicamento para ver la disponibilidad en tiempo real de farmacias verificadas.',
    searchPlaceholder: 'Buscar por medicamento, marca o genérico...',
    scanPrescription: 'Escanear una receta',
    scanDesc: 'Tome una foto o cárguela: extraemos los medicamentos por usted.',
    popularSearches: 'POPULARES:',
    apply: 'Aplicar',
    languageUpdated: 'Preferencia de idioma guardada',
    settingsSubtitle: 'Preferencias de idioma, accesibilidad y ubicación.',
    languageAndRegion: 'Idioma y región',
    chooseLanguage: 'Elija su idioma de interfaz preferido.',
    accessibility: 'Accesibilidad (WCAG 2.2 AA)',
    accessibilityDesc: 'Haga que la interfaz sea más fácil de leer y usar.',
    largerText: 'Texto más grande',
    largerTextDesc: 'Aumentar el tamaño del texto.',
    reduceMotion: 'Reducir movimiento',
    reduceMotionDesc: 'Minimizar animaciones y transiciones.',
    locationAndData: 'Ubicación y datos',
    clearLocationDesc: 'Borrar la ubicación guardada en este dispositivo.',
    clearLocationBtn: 'Borrar ubicación guardada',
    contactDetails: 'Detalles de contacto',
    updateContactDesc: 'Actualice cómo pueden comunicarse con usted.',
    fullName: 'Nombre completo',
    emailAddress: 'Correo electrónico',
    phone: 'Teléfono',
    saveChanges: 'Guardar cambios',
    password: 'Contraseña',
    updatePasswordDesc: 'Actualice la contraseña de su cuenta.',
    currentPassword: 'Contraseña actual',
    newPassword: 'Nueva contraseña',
    confirmNewPassword: 'Confirmar nueva contraseña',
    updatePasswordBtn: 'Actualizar contraseña',
    searchByName: 'Buscar por nombre',
    medicineName: 'NOMBRE DEL MEDICAMENTO',
    searchArea: 'ÁREA DE BÚSQUEDA',
    useMyLocation: 'Usar mi ubicación',
    usingCurrentLocation: 'Usando su ubicación actual',
    locationSet: 'Ubicación configurada',
    undo: 'Deshacer',
    searchAvailability: 'Buscar Disponibilidad',
    distanceFromMe: 'Distancia desde mí:',
    km: 'km',
    verifiedNetwork: 'Red de farmacias verificadas',
    privacySafe: 'Búsqueda segura para la privacidad',
    noExactQuantities: 'Sin cantidades exactas de stock',
    availabilityNearYou: 'Disponibilidad cerca de usted',
    whatDoesConfidenceMean: '¿Qué significa la confianza?',
    emptySearchPrompt: 'Ingrese un medicamento y toque Buscar Disponibilidad para ver qué farmacias cercanas es probable que lo tengan.',
    checkingAvailability: 'Comprobando disponibilidad en farmacias cercanas…',
    noPharmaciesFound: 'No se encontraron farmacias dentro del radio seleccionado. Pruebe una ubicación diferente o aumente la distancia.',
    directions: 'Indicaciones',
    callPharmacy: 'Llamar a la farmacia',
    save: 'Guardar',
    saved: 'Guardado',
    medicineNameHelp: 'Ingrese únicamente un nombre de medicamento. No ingrese síntomas, diagnósticos o fotos de recetas.',
    searchAreaPlaceholder: 'Ciudad, código postal',
    addLocationHelp: 'Agregue una ubicación para ver las farmacias cercanas.',
    understandingAvailability: 'Entendiendo la confianza de disponibilidad',
    availabilitySubtitle: 'Cómo ZoikoMeds muestra si es probable que un medicamento esté disponible cerca de usted.',
    whatIsZoikoAvail: '¿Qué es ZoikoAvail™?',
    whatIsZoikoAvailDesc: 'ZoikoAvail™ es el motor de confianza de disponibilidad de ZoikoMeds.',
    confidenceLevels: 'Niveles de confianza',
    whyAvailabilityChanges: 'Por qué cambia la disponibilidad de medicamentos',
    howPharmaciesKeepCurrent: 'Cómo lo mantienen actualizado las farmacias verificadas',
    verifiedPharmaciesOnly: 'Solo farmacias verificadas',
    verifiedPharmaciesOnlyDesc: 'Las señales provienen solo de farmacias verificadas.',
    signalsNotStock: 'Señales, no cantidades',
    signalsNotStockDesc: 'Nunca exponemos cantidades exactas de stock.',
    freshnessWeighted: 'Ponderado por frescura',
    freshnessWeightedDesc: 'ZoikoAvail™ pondera cada señal por qué tan reciente es.',
    searchMedicineAvailability: 'Buscar disponibilidad de medicamentos',
    likelyAvailableNow: 'Probablemente disponible ahora',
    likelyAvailableNowDesc: 'Una farmacia verificada compartió una señal reciente.',
    mayBeLimited: 'Puede ser limitado — confirme primero',
    mayBeLimitedDesc: 'Confirme con la farmacia antes de viajar.',
    notRecentlyConfirmed: 'No confirmado recientemente',
    notRecentlyConfirmedDesc: 'Llame antes de visitar.',
    noRecentSignal: 'Sin señal reciente',
    noRecentSignalDesc: 'No hay señal reciente de farmacias verificadas cercanas.',
    search: 'Buscar',
    availability: 'Disponibilidad',
    savedMedicinesSubtitle: 'Rastree la disponibilidad de sus medicamentos guardados.',
    noSavedMedicinesYet: 'Aún no hay medicamentos guardados',
    noSavedMedicinesDesc: 'Guarde un medicamento desde la búsqueda.',
    alertsEnabled: 'Alertas activadas',
    viewDetails: 'Ver detalles',
    recentSearches: 'Búsquedas recientes',
    verifiedPharmacies: 'Farmacias verificadas',
    activeAlerts: 'Alertas activas',
    yourZoikoSignal: 'Su ZoikoSignal™',
    zoikoSignalDesc: 'Obtenga alertas cuando sus medicamentos guardados tengan poco stock.',
    savedMedicinesDesc: 'Rastree la disponibilidad de los medicamentos que sigue.',
    feverPain: 'Fiebre y dolor',
    coldCough: 'Resfriado y tos',
    diabetes: 'Diabetes',
    heartBp: 'Corazón y presión',
    antibiotics: 'Antibióticos',
    acidity: 'Acidez',
    allergy: 'Alergias',
    vitamins: 'Vitaminas',
    homeDisclaimer: 'La disponibilidad es una señal de confianza — no stock exacto. Confirme antes de ir.',
    browseByHealthNeed: 'NAVEGAR POR NECESIDAD DE SALUD',
    zoikoSignalSubtitle: 'Notificaciones personalizadas de disponibilidad de medicamentos.',
    liveMonitoring: 'Monitoreo en vivo',
    markAllRead: 'Marcar todo como leído',
    runningLow: 'Poco stock',
    backInStockToday: 'De nuevo en stock hoy',
    allCaughtUp: 'Está al día',
    noUrgentAlerts: 'No hay alertas urgentes en este momento.',
    mySavedMedicines: 'MIS MEDICAMENTOS GUARDADOS',
    searchSavedPlaceholder: 'Buscar medicamentos guardados...',
    smartNotifications: 'NOTIFICACIONES INTELIGENTES',
    all: 'Todos',
    unread: 'No leídos',
    safetyAlerts: 'Alertas de seguridad',
    viewPharmacies: 'Ver farmacias',
    markRead: 'Marcar como leído',
    archive: 'Archivar',
    readAdvisory: 'Leer aviso',
    readAnnouncement: 'Leer anuncio',
    notificationsSubtitle: 'Actualizaciones de la plataforma y alertas de seguridad.',
    announcements: 'Anuncios',
    stockAlerts: 'Alertas de stock',
    safetyRecalls: 'Seguridad y retiradas',
    system: 'Sistema',
    noNotifications: 'Sin notificaciones',
    notificationSettings: 'Configuración de notificaciones',
    notificationSettingsDesc: 'Elija sobre qué le informa ZoikoSignal™.',
    availabilityAlerts: 'Alertas de disponibilidad',
    runningLowTitle: 'Poco stock',
    runningLowDesc: 'Notificarme cuando un medicamento guardado tenga poco stock cerca de mí.',
    backInStockTitle: 'De nuevo en stock',
    backInStockDesc: 'Notificarme cuando un medicamento guardado esté disponible nuevamente.',
    nearbyRestockTitle: 'Reabastecimiento cercano',
    nearbyRestockDesc: 'Notificarme cuando una farmacia cercana reciba nuevo stock.',
    safetyHeading: 'Seguridad',
    medicineRecallTitle: 'Alertas de retirada de medicamentos',
    medicineRecallDesc: 'Avisos de retirada para los medicamentos que sigue.',
    governmentSafetyTitle: 'Alertas de seguridad gubernamentales',
    governmentSafetyDesc: 'Avisos de salud nacionales para sus categorías de medicamentos.',
    channelsHeading: 'Canales',
    pushNotificationsTitle: 'Notificaciones push',
    pushNotificationsDesc: 'Recibir alertas en este dispositivo.',
    emailNotificationsTitle: 'Email notifications',
    emailNotificationsDesc: 'Recibir un resumen por correo electrónico.',
    smsNotificationsTitle: 'SMS notifications',
    smsNotificationsDesc: 'Recibir alertas urgentes por mensaje de texto.',
    whyChange1: 'Las farmacias dispensan existencias a lo largo del día, por lo que lo disponible esta mañana puede no estarlo por la tarde.',
    whyChange2: 'Los nuevos envíos y reabastecimientos llegan en diferentes horarios para cada farmacia.',
    whyChange3: 'La demanda regional y la presión de suministro cambian la disponibilidad rápidamente.',
    whyChange4: 'Una señal envejece: cuanto más tiempo pase desde la última confirmación, menor será la confianza.',
    confirmNote: 'La disponibilidad es una señal de confianza de farmacias verificadas, no stock exacto. Confirme con la farmacia antes de viajar.',
    scopeNote: 'ZoikoMeds muestra dónde pueden estar disponibles los medicamentos. No es una farmacia ni un servicio de entrega.',
    verifiedAccount: 'Cuenta verificada',
    readOnly: 'SOLO LECTURA',
    emailReadOnlyNotice: 'El correo electrónico está vinculado a su cuenta y no se puede cambiar.',
    profilePrivacyNotice: 'ZoikoMeds no recopila recetas ni historiales médicos.',
    profileUpdated: 'Perfil actualizado',
    passwordUpdated: 'Contraseña actualizada',
    enterPassword: 'Ingrese la contraseña',
    passwordMinLength: 'La contraseña debe tener al menos 8 caracteres.',
    passwordsDoNotMatch: 'Las contraseñas no coinciden.',
    dropPrescriptionHere: 'Suelte su receta aquí',
    extractMedicineDesc: 'Extraeremos los nombres de los medicamentos; usted elige cuáles buscar.',
    browseFile: 'Buscar archivo',
    maxFileNotice: 'JPG, PNG, PDF, HEIC — máx 10 MB',
    or: 'o',
    takePhoto: 'Tomar foto',
    fromGallery: 'De la galería',
    privacyNoticeTitle: 'Aviso de privacidad:',
    prescriptionPrivacyNotice: 'La imagen de su receta se usa únicamente para extraer nombres de medicamentos para esta búsqueda.',
    yourLocationForNearbySearch: 'Su ubicación (para búsqueda cercana)',
    useMyCurrentLocation: 'Usar mi ubicación actual',
    medicinesFound: 'Medicamentos encontrados',
    scanAnother: 'Escanear otro',
    chooseMedicinesToSearch: 'Elija qué medicamentos buscar para disponibilidad cercana.',
    extractedNamesNotice: 'Los nombres extraídos se leen únicamente de su imagen. Confirme el medicamento exacto con su receta.',
    readingPrescription: 'Leyendo su receta…',
    extractingNamesFrom: 'Extrayendo nombres de medicamentos',
    deviceOnlyNotice: 'Esto sucede en su dispositivo — la imagen no se carga.',
    prescription: 'Receta',
    otc: 'Venta libre (OTC)',
    governedIdentityNotice: 'Identidad de medicamento gobernada — MediBase™. La disponibilidad es una señal de confianza.',
    requiresConfirmation: 'Requiere confirmación — llame antes de visitar.',
    distance: 'Distancia',
    signalUpdated: 'Señal actualizada',
    call: 'Llamar',
    morePharmaciesWeb: 'Más farmacias cerca de usted (de la web)',
    openNow: 'Abierto ahora',
    closed: 'Cerrado',
    rating: 'Calificación',
    webPharmaciesDisclaimer: 'Encontrado en la web por ubicación. El stock no está confirmado — llame con anticipación.',
    howAvailabilityWorksCaps: 'CÓMO FUNCIONA LA DISPONIBILIDAD',
    medibaseIdentifies: 'MediBase™ identifica el medicamento',
    medibaseDesc: 'Las marcas, genéricos y concentraciones se asignan a una identidad gobernada.',
    zoikoAvailScores: 'ZoikoAvail™ evalúa la confianza',
    zoikoAvailDescSummary: 'Las señales de farmacias verificadas se ponderan por frescura y confiabilidad.',
    confirmBeforeVisiting: 'Confirme antes de visitar',
    confirmBeforeVisitingDesc: 'Mostramos confianza, nunca stock exacto. Confirme siempre con la farmacia.',
    nearbyVerifiedPharmacies: 'FARMACIAS VERIFICADAS CERCANAS',
    confidenceLabel: 'Confianza:',
    confidenceHigh: 'Alta',
    confidenceModerate: 'Moderada',
    confidenceLow: 'Baja',
    featuredMedicines: 'MEDICAMENTOS DESTACADOS',
    recentSearchesCaps: 'BÚSQUEDAS RECIENTES',
    noNewSignals: 'No hay nuevas señales para sus medicamentos guardados.',
    viewAll: 'Ver todo',
    lastConfirmed: 'Última confirmación',
    checkAvailability: 'Consultar disponibilidad',
    confirmed: 'Confirmado',
    savedLocationCleared: 'Ubicación guardada eliminada',
    of: 'de',
    pharmacies: 'farmacias',
    new: 'nuevo',
    isBackInStock: 'está de nuevo en stock',
    hasLimitedAvailability: 'tiene disponibilidad limitada',
    isRunningLow: 'se está agotando',
    doesAvailabilityMeanInStock: '¿La disponibilidad significa que el medicamento está en stock?',
    disclaimerDetails: 'ZoikoMeds solo proporciona inteligencia de disponibilidad y no garantiza el stock. Confirme siempre con la farmacia.',
    confidenceUnknown: 'Desconocido',
    medicineNotFound: 'Medicamento no encontrado',
    backToSearch: 'Volver a la búsqueda',
    generic: 'Genérico',
    savedMedicine: 'Medicamento guardado',
    saveMedicine: 'Guardar medicamento',
    findNearMe: 'Buscar cerca de mí',
    medicineInformation: 'Información del medicamento',
    brandName: 'Nombre de marca',
    genericName: 'Nombre genérico',
    strength: 'Dosis',
    dosageForm: 'Forma farmacéutica',
    route: 'Vía de administración',
    manufacturer: 'Fabricante',
    alsoSoldAs: 'También vendido como',
    category: 'Categoría',
    availabilityNow: 'Disponibilidad actual',
    availablePharmacies: 'Farmacias disponibles',
    brandAlternatives: 'Alternativas de marca',
    genericAlternatives: 'Alternativas genéricas',
    frequentlyAskedQuestions: 'Preguntas frecuentes',
    setDeliveryLocationTitle: 'Establecer su ubicación de entrega',
    deliveryLocationDesc: 'Ingrese una ciudad, área o código PIN de 6 dígitos para consultar la disponibilidad.',
    deliveryLocationPlaceholder: 'ej. Madrid, Nizampet o 500043',
    enterCityOrPinCode: 'Por favor ingrese una ciudad, área o código PIN de 6 dígitos.',
    networkErrorVerifyingLocation: 'Error de red al verificar la ubicación. Vuelva a intentarlo.',
    noMatchingLocationFound: 'No se encontró ninguna ubicación coincidente.',
    liveGeocodingSuggestions: 'Sugerencias de geocodificación en vivo',
    recentLocations: 'Ubicaciones recientes:',
    cancel: 'Cancelar',
    verifying: 'Verificando...',
    saveLocation: 'Guardar ubicación',
    retry: 'Reintentar',
    contactDetailsDescSubtitle: 'Gestione sus datos de contacto y la seguridad de su cuenta.',
    validPhone: 'Por favor ingrese un número de teléfono válido.',
    validIndianMobile: 'Por favor ingrese un número de móvil indio válido.',
    phoneTooShort: 'El número de teléfono es demasiado corto.',
    phoneTooLong: 'El número de teléfono es demasiado largo.',
    invalidPhoneCountry: 'Número de teléfono no válido para el país seleccionado.',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem('zoiko-lang') || 'en')

  useEffect(() => {
    const handleLangChange = () => {
      const saved = localStorage.getItem('zoiko-lang') || 'en'
      setLangState(saved)
      document.documentElement.lang = saved
    }

    window.addEventListener('zoiko-language-change', handleLangChange)
    window.addEventListener('storage', handleLangChange)
    return () => {
      window.removeEventListener('zoiko-language-change', handleLangChange)
      window.removeEventListener('storage', handleLangChange)
    }
  }, [])

  const setLanguage = useCallback((newLang) => {
    localStorage.setItem('zoiko-lang', newLang)
    setLangState(newLang)
    document.documentElement.lang = newLang
    window.dispatchEvent(new Event('storage'))
    window.dispatchEvent(new Event('zoiko-language-change'))
  }, [])

  const t = useCallback(
    (key, fallback = '') => {
      const dict = TRANSLATIONS[lang] || TRANSLATIONS.en
      return dict[key] || TRANSLATIONS.en[key] || fallback || key
    },
    [lang]
  )

  const value = useMemo(
    () => ({
      language: lang,
      setLanguage,
      t,
      translations: TRANSLATIONS[lang] || TRANSLATIONS.en,
    }),
    [lang, setLanguage, t]
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) {
    const currentLang = localStorage.getItem('zoiko-lang') || 'en'
    return {
      language: currentLang,
      setLanguage: (l) => {
        localStorage.setItem('zoiko-lang', l)
        window.dispatchEvent(new Event('zoiko-language-change'))
      },
      t: (k, fb) => (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][k]) || TRANSLATIONS.en[k] || fb || k,
      translations: TRANSLATIONS[currentLang] || TRANSLATIONS.en,
    }
  }
  return ctx
}
