import { createContext, useContext, useState, useEffect, useMemo, useCallback } from 'react'

const LanguageContext = createContext(null)

export const LANG_NAMES = {
  en: 'English (India)',
  hi: 'हिन्दी (Hindi)',
  te: 'తెలుగు (Telugu)',
  es: 'Español (Spanish)',
}

const TRANSLATIONS = {
  en: {
    home: 'Home',
    searchMedicines: 'Search Medicines',
    howAvailabilityWorks: 'How Availability Works',
    savedMedicines: 'Saved Medicines',
    zoikoSignal: 'ZoikoSignal™',
    notifications: 'Notifications',
    myProfile: 'My Profile',
    settings: 'Settings',
    helpSupport: 'Help & Support',
    signOut: 'Sign Out',
    myMedicines: 'My Medicines',
    account: 'Account',
    support: 'Support',
    findAvailability: 'Find medicine availability near you',
    heroSubtitle: 'Search a medicine to see real-time availability confidence from verified pharmacies — powered by MediBase™ and governed data.',
    searchPlaceholder: 'Search by medicine, brand name, active ingredient, or generic...',
    scanPrescription: 'Scan a prescription',
    scanDesc: 'Snap or upload it — we extract the medicines for you.',
    popularSearches: 'POPULAR:',
    apply: 'Apply',
    languageUpdated: 'Language preference updated',
    settingsSubtitle: 'Language, accessibility, and location preferences.',
    languageAndRegion: 'Language & region',
    chooseLanguage: 'Choose your preferred interface language.',
    accessibility: 'Accessibility (WCAG 2.2 AA)',
    accessibilityDesc: 'Make the interface easier to read and use.',
    largerText: 'Larger text',
    largerTextDesc: 'Increase label and body text size.',
    reduceMotion: 'Reduce motion',
    reduceMotionDesc: 'Minimize animations and transitions.',
    locationAndData: 'Location & data',
    clearLocationDesc: 'Clear the location saved on this device.',
    clearLocationBtn: 'Clear saved location',
    contactDetails: 'Contact details',
    updateContactDesc: 'Update how verified pharmacies and ZoikoMeds can reach you.',
    fullName: 'Full name',
    emailAddress: 'Email address',
    phone: 'Phone',
    saveChanges: 'Save changes',
    password: 'Password',
    updatePasswordDesc: 'Update your account password.',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmNewPassword: 'Confirm new password',
    updatePasswordBtn: 'Update password',
    searchByName: 'Search by name',
    medicineName: 'MEDICINE NAME',
    searchArea: 'SEARCH AREA',
    useMyLocation: 'Use my location',
    usingCurrentLocation: 'Using your current location',
    locationSet: 'Location set',
    undo: 'Undo',
    searchAvailability: 'Search Availability',
    distanceFromMe: 'Distance from me:',
    miles: 'miles',
    verifiedNetwork: 'Verified pharmacy network',
    privacySafe: 'Privacy-safe search',
    noExactQuantities: 'No exact stock quantities',
    availabilityNearYou: 'Availability near you',
    whatDoesConfidenceMean: 'What does confidence mean?',
    emptySearchPrompt: 'Enter a medicine and tap Search Availability to see which nearby pharmacies are likely to have it.',
    checkingAvailability: 'Checking availability at nearby pharmacies…',
    noPharmaciesFound: 'No pharmacies found within the selected radius. Try a different location or increase the distance.',
    directions: 'Directions',
    callPharmacy: 'Call pharmacy',
    save: 'Save',
    saved: 'Saved',
    medicineNameHelp: 'Enter a medicine name only. Do not enter symptoms, diagnoses, insurance details, or prescription images.',
    searchAreaPlaceholder: 'City, ZIP code, or postcode',
    addLocationHelp: 'Add a location to see nearby pharmacies.',
  },
  hi: {
    home: 'होम',
    searchMedicines: 'दवाइयां खोजें',
    howAvailabilityWorks: 'उपलब्धता प्रक्रिया',
    savedMedicines: 'सहेजी गई दवाएं',
    zoikoSignal: 'ज़ोइको सिग्नल™',
    notifications: 'सूचनाएं',
    myProfile: 'मेरी प्रोफाइल',
    settings: 'सेटिंग्स',
    helpSupport: 'सहायता एवं समर्थन',
    signOut: 'साइन आउट',
    myMedicines: 'मेरी दवाइयां',
    account: 'खाता',
    support: 'सहायता',
    findAvailability: 'अपने पास दवाओं की उपलब्धता खोजें',
    heroSubtitle: 'सत्यापित फार्मेसियों से रीयल-टाइम उपलब्धता देखने के लिए कोई भी दवा खोजें — मेडीबेस™ द्वारा संचालित।',
    searchPlaceholder: 'दवा का नाम, ब्रांड, या सॉल्ट खोजें...',
    scanPrescription: 'प्रिस्क्रिप्शन स्कैन करें',
    scanDesc: 'फोटो खींचें या अपलोड करें — हम दवाओं का नाम निकाल देंगे।',
    popularSearches: 'लोकप्रिय खोजें:',
    apply: 'लागू करें',
    languageUpdated: 'भाषा सफलतापूर्वक बदल दी गई',
    settingsSubtitle: 'भाषा, सुगमता और स्थान प्राथमिकताएं।',
    languageAndRegion: 'भाषा और क्षेत्र',
    chooseLanguage: 'अपनी पसंदीदा इंटरफ़ेस भाषा चुनें।',
    accessibility: 'सुगमता (Accessibility)',
    accessibilityDesc: 'इंटरफ़ेस को पढ़ने और उपयोग करने में आसान बनाएं।',
    largerText: 'बड़ा टेक्स्ट',
    largerTextDesc: 'लेबल और बॉडी टेक्स्ट का आकार बढ़ाएं।',
    reduceMotion: 'मोशन कम करें',
    reduceMotionDesc: 'एनिमेशन और ट्रांज़िशन को कम करें।',
    locationAndData: 'स्थान और डेटा',
    clearLocationDesc: 'इस डिवाइस पर सहेजे गए स्थान को हटाएं।',
    clearLocationBtn: 'सहेजा गया स्थान हटाएं',
    contactDetails: 'संपर्क विवरण',
    updateContactDesc: 'अपडेट करें कि सत्यापित फ़ार्मेसियां और ZoikoMeds आपसे कैसे संपर्क कर सकते हैं।',
    fullName: 'पूरा नाम',
    emailAddress: 'ईमेल पता',
    phone: 'फ़ोन',
    saveChanges: 'परिवर्तन सहेजें',
    password: 'पासवर्ड',
    updatePasswordDesc: 'अपना खाता पासवर्ड अपडेट करें।',
    currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नया पासवर्ड',
    confirmNewPassword: 'नए पासवर्ड की पुष्टि करें',
    updatePasswordBtn: 'पासवर्ड अपडेट करें',
    searchByName: 'नाम से खोजें',
    medicineName: 'दवा का नाम',
    searchArea: 'खोज क्षेत्र',
    useMyLocation: 'मेरे स्थान का उपयोग करें',
    usingCurrentLocation: 'आपके वर्तमान स्थान का उपयोग कर रहा है',
    locationSet: 'स्थान सेट किया गया',
    undo: 'पूर्ववत करें',
    searchAvailability: 'उपलब्धता खोजें',
    distanceFromMe: 'मुझसे दूरी:',
    miles: 'मील',
    verifiedNetwork: 'सत्यापित फार्मेसी नेटवर्क',
    privacySafe: 'गोपनीयता-सुरक्षित खोज',
    noExactQuantities: 'कोई सटीक स्टॉक मात्रा नहीं',
    availabilityNearYou: 'आपके पास उपलब्धता',
    whatDoesConfidenceMean: 'विश्वास का क्या अर्थ है?',
    emptySearchPrompt: 'एक दवा दर्ज करें और यह देखने के लिए उपलब्धता खोजें पर टैप करें कि किन नजदीकी फार्मेसियों में इसके होने की संभावना है।',
    checkingAvailability: 'नजदीकी फार्मेसियों में उपलब्धता की जांच की जा रही है…',
    noPharmaciesFound: 'चयनित त्रिज्या के भीतर कोई फार्मेसी नहीं मिली। कोई भिन्न स्थान आज़माएं या दूरी बढ़ाएं।',
    directions: 'दिशा-निर्देश',
    callPharmacy: 'फार्मेसी को कॉल करें',
    save: 'सहेजें',
    saved: 'सहेजा गया',
    medicineNameHelp: 'केवल दवा का नाम दर्ज करें। लक्षण, निदान, बीमा विवरण या नुस्खे की छवियां दर्ज न करें।',
    searchAreaPlaceholder: 'शहर, पिन कोड या पोस्टकोड',
    addLocationHelp: 'आस-पास की फार्मेसियों को देखने के लिए स्थान जोड़ें।',
  },
  te: {
    home: 'హోమ్',
    searchMedicines: 'మందుల శోధన',
    howAvailabilityWorks: 'లభ్యత ప్రక్రియ',
    savedMedicines: 'సేవ్ చేసిన మందులు',
    zoikoSignal: 'జోయికో సిగ్నల్™',
    notifications: 'నోటిఫికేషన్లు',
    myProfile: 'నా ప్రొఫైల్',
    settings: 'సెట్టింగ్‌లు',
    helpSupport: 'సహాయం & మద్దతు',
    signOut: 'సైన్ అవుట్',
    myMedicines: 'నా మందులు',
    account: 'ఖాతా',
    support: 'సహాయం',
    findAvailability: 'మీ సమీపంలో మందుల లభ్యతను శోధించండి',
    heroSubtitle: 'తనిఖీ చేయబడిన ఫార్మసీల నుండి నిజ-సమయ లభ్యత సమాచారాన్ని చూడటానికి శోధించండి.',
    searchPlaceholder: 'మందు పేరు లేదా బ్రాండ్ నమోదు చేయండి...',
    scanPrescription: 'ప్రిస్క్రిప్షన్ స్కాన్ చేయండి',
    scanDesc: 'ఫోటో లేదా ఫైల్ అప్‌లోడ్ చేయండి — మేము వివరాలు తీస్తాము.',
    popularSearches: 'ప్రజాదరణ పొందినవి:',
    apply: 'వర్తింపజేయి',
    languageUpdated: 'భాష విజయవంతంగా మార్చబడింది',
    settingsSubtitle: 'భాష, యాక్సెసిబిలిటీ మరియు స్థాన ప్రాధాన్యతలు.',
    languageAndRegion: 'భాష & ప్రాంతం',
    chooseLanguage: 'మీకు కావలసిన భాషను ఎంచుకోండి.',
    accessibility: 'యాక్సెసిబిలిటీ (Accessibility)',
    accessibilityDesc: 'ఇంటర్‌ఫేస్‌ను చదవడానికి మరియు ఉపయోగించడానికి సులభతరం చేయండి.',
    largerText: 'పెద్ద అక్షరాలు',
    largerTextDesc: 'అక్షరాల పరిమాణాన్ని పెంచండి.',
    reduceMotion: 'మోషన్ తగ్గించండి',
    reduceMotionDesc: 'యానిమేషన్లను తగ్గించండి.',
    locationAndData: 'స్థానం & డేటా',
    clearLocationDesc: 'ఈ పరికరంలో సేవ్ చేసిన స్థానాన్ని తొలగించండి.',
    clearLocationBtn: 'సేవ్ చేసిన స్థానాన్ని తొలగించు',
    contactDetails: 'సంప్రదింపు వివరాలు',
    updateContactDesc: 'మిమ్మల్ని సంప్రదించడానికి వివరాలను నవీకరించండి.',
    fullName: 'పూర్తి పేరు',
    emailAddress: 'ఈమెయిల్ చిరునామా',
    phone: 'ఫోన్ సంఖ్య',
    saveChanges: 'మార్పులను సేవ్ చేయి',
    password: 'పాస్‌వర్డ్',
    updatePasswordDesc: 'మీ ఖాతా పాస్‌వర్డ్‌ను నవీకరించండి.',
    currentPassword: 'ప్రస్తుత పాస్‌వర్డ్',
    newPassword: 'కొత్త పాస్‌వర్డ్',
    confirmNewPassword: 'కొత్త పాస్‌వర్డ్‌ను ధృవీకరించండి',
    updatePasswordBtn: 'పాస్‌వర్డ్ నవీకరించు',
    searchByName: 'పేరు ద్వారా శోధించండి',
    medicineName: 'మందు పేరు',
    searchArea: 'శోధన ప్రాంతం',
    useMyLocation: 'నా స్థానాన్ని ఉపయోగించు',
    usingCurrentLocation: 'మీ ప్రస్తుత స్థానాన్ని ఉపయోగిస్తోంది',
    locationSet: 'స్థానం సెట్ చేయబడింది',
    undo: 'రద్దు చేయి',
    searchAvailability: 'లభ్యత శోధించండి',
    distanceFromMe: 'నా నుండి దూరం:',
    miles: 'మైళ్ళు',
    verifiedNetwork: 'ప్రామాణీకరించబడిన ఫార్మసీ నెట్‌వర్క్',
    privacySafe: 'గోప్యతా-సురక్షిత శోధన',
    noExactQuantities: 'కచ్చితమైన నిల్వ పరిమాణాలు లేవు',
    availabilityNearYou: 'మీ సమీపంలో లభ్యత',
    whatDoesConfidenceMean: 'విశ్వసనీయత అంటే ఏమిటి?',
    emptySearchPrompt: 'ఒక మందును నమోదు చేసి, సమీపంలోని ఏ ఫార్మసీలలో అది ఉండవచ్చో చూడటానికి లభ్యత శోధించండి నొక్కండి.',
    checkingAvailability: 'సమీపంలోని ఫార్మసీలలో లభ్యతను తనిఖీ చేస్తోంది…',
    noPharmaciesFound: 'ఎంచుకున్న పరిధిలో ఫార్మసీలు ఏవీ కనుగొనబడలేదు. విభిన్న స్థానాన్ని ప్రయత్నించండి లేదా దూరాన్ని పెంచండి.',
    directions: 'దిశలు',
    callPharmacy: 'ఫార్మసీకి కాల్ చేయండి',
    save: 'సేవ్ చేయి',
    saved: 'సేవ్ చేయబడింది',
    medicineNameHelp: 'మందు పేరు మాత్రమే నమోదు చేయండి. లక్షణాలు, భీమా వివరాలు లేదా ప్రిస్క్రిప్షన్ చిత్రాలను నమోదు చేయవద్దు.',
    searchAreaPlaceholder: 'నగరం, పిన్ కోడ్ లేదా పోస్ట్‌కోడ్',
    addLocationHelp: 'సమీపంలోని ఫార్మసీలను చూడటానికి ఒక స్థానాన్ని జోడించండి.',
  },
  es: {
    home: 'Inicio',
    searchMedicines: 'Buscar Medicamentos',
    howAvailabilityWorks: 'Cómo funciona la disponibilidad',
    savedMedicines: 'Medicamentos Guardados',
    zoikoSignal: 'ZoikoSignal™',
    notifications: 'Notificaciones',
    myProfile: 'Mi Perfil',
    settings: 'Configuración',
    helpSupport: 'Ayuda y Soporte',
    signOut: 'Cerrar Sesión',
    myMedicines: 'Mis Medicamentos',
    account: 'Cuenta',
    support: 'Soporte',
    findAvailability: 'Busque disponibilidad de medicamentos cerca de usted',
    heroSubtitle: 'Busque un medicamento para ver la disponibilidad en tiempo real de farmacias verificadas.',
    searchPlaceholder: 'Buscar por medicamento, marca o genérico...',
    scanPrescription: 'Escanear una receta',
    scanDesc: 'Tome una foto o cárguela: extraemos los medicamentos por usted.',
    popularSearches: 'POPULARES:',
    apply: 'Aplicar',
    languageUpdated: 'Preferencia de idioma guardada',
    settingsSubtitle: 'Preferencias de idioma, accesibilidad y ubicación.',
    languageAndRegion: 'Idioma y región',
    chooseLanguage: 'Elija su idioma de interfaz preferido.',
    accessibility: 'Accesibilidad (WCAG 2.2 AA)',
    accessibilityDesc: 'Haga que la interfaz sea más fácil de leer y usar.',
    largerText: 'Texto más grande',
    largerTextDesc: 'Aumentar el tamaño del texto.',
    reduceMotion: 'Reducir movimiento',
    reduceMotionDesc: 'Minimizar animaciones y transiciones.',
    locationAndData: 'Ubicación y datos',
    clearLocationDesc: 'Borrar la ubicación guardada en este dispositivo.',
    clearLocationBtn: 'Borrar ubicación guardada',
    contactDetails: 'Detalles de contacto',
    updateContactDesc: 'Actualice cómo pueden comunicarse con usted.',
    fullName: 'Nombre completo',
    emailAddress: 'Correo electrónico',
    phone: 'Teléfono',
    saveChanges: 'Guardar cambios',
    password: 'Contraseña',
    updatePasswordDesc: 'Actualice la contraseña de su cuenta.',
    currentPassword: 'Contraseña actual',
    newPassword: 'Nueva contraseña',
    confirmNewPassword: 'Confirmar nueva contraseña',
    updatePasswordBtn: 'Actualizar contraseña',
    searchByName: 'Buscar por nombre',
    medicineName: 'NOMBRE DEL MEDICAMENTO',
    searchArea: 'ÁREA DE BÚSQUEDA',
    useMyLocation: 'Usar mi ubicación',
    usingCurrentLocation: 'Usando su ubicación actual',
    locationSet: 'Ubicación configurada',
    undo: 'Deshacer',
    searchAvailability: 'Buscar Disponibilidad',
    distanceFromMe: 'Distancia desde mí:',
    miles: 'millas',
    verifiedNetwork: 'Red de farmacias verificadas',
    privacySafe: 'Búsqueda segura para la privacidad',
    noExactQuantities: 'Sin cantidades exactas de stock',
    availabilityNearYou: 'Disponibilidad cerca de usted',
    whatDoesConfidenceMean: '¿Qué significa la confianza?',
    emptySearchPrompt: 'Ingrese un medicamento y toque Buscar Disponibilidad para ver qué farmacias cercanas es probable que lo tengan.',
    checkingAvailability: 'Comprobando disponibilidad en farmacias cercanas…',
    noPharmaciesFound: 'No se encontraron farmacias dentro del radio seleccionado. Pruebe una ubicación diferente o aumente la distancia.',
    directions: 'Indicaciones',
    callPharmacy: 'Llamar a la farmacia',
    save: 'Guardar',
    saved: 'Guardado',
    medicineNameHelp: 'Ingrese únicamente un nombre de medicamento. No ingrese síntomas, diagnósticos o fotos de recetas.',
    searchAreaPlaceholder: 'Ciudad, código postal',
    addLocationHelp: 'Agregue una ubicación para ver las farmacias cercanas.',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem('zoiko-lang') || 'en')

  useEffect(() => {
    const handleLangChange = () => {
      const saved = localStorage.getItem('zoiko-lang') || 'en'
      setLangState(saved)
      document.documentElement.lang = saved
    }

    window.addEventListener('zoiko-language-change', handleLangChange)
    window.addEventListener('storage', handleLangChange)
    return () => {
      window.removeEventListener('zoiko-language-change', handleLangChange)
      window.removeEventListener('storage', handleLangChange)
    }
  }, [])

  const setLanguage = useCallback((newLang) => {
    localStorage.setItem('zoiko-lang', newLang)
    setLangState(newLang)
    document.documentElement.lang = newLang
    window.dispatchEvent(new Event('storage'))
    window.dispatchEvent(new Event('zoiko-language-change'))
  }, [])

  const t = useCallback(
    (key, fallback = '') => {
      const dict = TRANSLATIONS[lang] || TRANSLATIONS.en
      return dict[key] || TRANSLATIONS.en[key] || fallback || key
    },
    [lang]
  )

  const value = useMemo(
    () => ({
      language: lang,
      setLanguage,
      t,
      translations: TRANSLATIONS[lang] || TRANSLATIONS.en,
    }),
    [lang, setLanguage, t]
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) {
    const currentLang = localStorage.getItem('zoiko-lang') || 'en'
    return {
      language: currentLang,
      setLanguage: (l) => {
        localStorage.setItem('zoiko-lang', l)
        window.dispatchEvent(new Event('zoiko-language-change'))
      },
      t: (k, fb) => (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][k]) || TRANSLATIONS.en[k] || fb || k,
      translations: TRANSLATIONS[currentLang] || TRANSLATIONS.en,
    }
  }
  return ctx
}
